// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tracking

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ExperimentResult struct {
	ArtifactLocation string            `pulumi:"artifactLocation"`
	ExperimentId     string            `pulumi:"experimentId"`
	LifecycleStage   string            `pulumi:"lifecycleStage"`
	Name             string            `pulumi:"name"`
	Tags             map[string]string `pulumi:"tags"`
}

type ExperimentResultOutput struct{ *pulumi.OutputState }

func (ExperimentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ExperimentResult)(nil)).Elem()
}

func (o ExperimentResultOutput) ToExperimentResultOutput() ExperimentResultOutput {
	return o
}

func (o ExperimentResultOutput) ToExperimentResultOutputWithContext(ctx context.Context) ExperimentResultOutput {
	return o
}

func (o ExperimentResultOutput) ArtifactLocation() pulumi.StringOutput {
	return o.ApplyT(func(v ExperimentResult) string { return v.ArtifactLocation }).(pulumi.StringOutput)
}

func (o ExperimentResultOutput) ExperimentId() pulumi.StringOutput {
	return o.ApplyT(func(v ExperimentResult) string { return v.ExperimentId }).(pulumi.StringOutput)
}

func (o ExperimentResultOutput) LifecycleStage() pulumi.StringOutput {
	return o.ApplyT(func(v ExperimentResult) string { return v.LifecycleStage }).(pulumi.StringOutput)
}

func (o ExperimentResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v ExperimentResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o ExperimentResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v ExperimentResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

type ExperimentResultArrayOutput struct{ *pulumi.OutputState }

func (ExperimentResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ExperimentResult)(nil)).Elem()
}

func (o ExperimentResultArrayOutput) ToExperimentResultArrayOutput() ExperimentResultArrayOutput {
	return o
}

func (o ExperimentResultArrayOutput) ToExperimentResultArrayOutputWithContext(ctx context.Context) ExperimentResultArrayOutput {
	return o
}

func (o ExperimentResultArrayOutput) Index(i pulumi.IntInput) ExperimentResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ExperimentResult {
		return vs[0].([]ExperimentResult)[vs[1].(int)]
	}).(ExperimentResultOutput)
}

func init() {
	pulumi.RegisterOutputType(ExperimentResultOutput{})
	pulumi.RegisterOutputType(ExperimentResultArrayOutput{})
}
