# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

insecureSkipVerify: Optional[bool]
"""
Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
"""

password: str
"""
Password for HTTP Basic authentication.
"""

token: str
"""
Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
"""

trackingUri: str
"""
URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
"""

username: str
"""
Username for HTTP Basic authentication against the MLflow tracking server.
"""

