# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('mlflow')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def insecure_skip_verify(self) -> Optional[bool]:
        """
        Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
        """
        return __config__.get_bool('insecureSkipVerify')

    @_builtins.property
    def password(self) -> str:
        """
        Password for HTTP Basic authentication.
        """
        return __config__.get('password') or (_utilities.get_env('MLFLOW_TRACKING_PASSWORD') or '')

    @_builtins.property
    def token(self) -> str:
        """
        Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
        """
        return __config__.get('token') or (_utilities.get_env('MLFLOW_TRACKING_TOKEN') or '')

    @_builtins.property
    def tracking_uri(self) -> str:
        """
        URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
        """
        return __config__.get('trackingUri') or (_utilities.get_env('MLFLOW_TRACKING_URI') or '')

    @_builtins.property
    def username(self) -> str:
        """
        Username for HTTP Basic authentication against the MLflow tracking server.
        """
        return __config__.get('username') or (_utilities.get_env('MLFLOW_TRACKING_USERNAME') or '')

