// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the latest version of a registered model per stage (or overall).
//
// REST: `/api/2.0/mlflow/registered-models/get-latest-versions`.
//
// ## Example Usage
func GetLatestVersions(ctx *pulumi.Context, args *GetLatestVersionsArgs, opts ...pulumi.InvokeOption) (*GetLatestVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLatestVersionsResult
	err := ctx.Invoke("mlflow:registry:getLatestVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetLatestVersionsArgs struct {
	Name   string   `pulumi:"name"`
	Stages []string `pulumi:"stages"`
}

type GetLatestVersionsResult struct {
	ModelVersions []ModelVersionResult `pulumi:"modelVersions"`
}

func GetLatestVersionsOutput(ctx *pulumi.Context, args GetLatestVersionsOutputArgs, opts ...pulumi.InvokeOption) GetLatestVersionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLatestVersionsResultOutput, error) {
			args := v.(GetLatestVersionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:getLatestVersions", args, GetLatestVersionsResultOutput{}, options).(GetLatestVersionsResultOutput), nil
		}).(GetLatestVersionsResultOutput)
}

type GetLatestVersionsOutputArgs struct {
	Name   pulumi.StringInput      `pulumi:"name"`
	Stages pulumi.StringArrayInput `pulumi:"stages"`
}

func (GetLatestVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLatestVersionsArgs)(nil)).Elem()
}

type GetLatestVersionsResultOutput struct{ *pulumi.OutputState }

func (GetLatestVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLatestVersionsResult)(nil)).Elem()
}

func (o GetLatestVersionsResultOutput) ToGetLatestVersionsResultOutput() GetLatestVersionsResultOutput {
	return o
}

func (o GetLatestVersionsResultOutput) ToGetLatestVersionsResultOutputWithContext(ctx context.Context) GetLatestVersionsResultOutput {
	return o
}

func (o GetLatestVersionsResultOutput) ModelVersions() ModelVersionResultArrayOutput {
	return o.ApplyT(func(v GetLatestVersionsResult) []ModelVersionResult { return v.ModelVersions }).(ModelVersionResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLatestVersionsResultOutput{})
}
