// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the artifact download URI for a model version.
//
// REST: `/api/2.0/mlflow/model-versions/get-download-uri`.
//
// ## Example Usage
func GetModelVersionDownloadUri(ctx *pulumi.Context, args *GetModelVersionDownloadUriArgs, opts ...pulumi.InvokeOption) (*GetModelVersionDownloadUriResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetModelVersionDownloadUriResult
	err := ctx.Invoke("mlflow:registry:getModelVersionDownloadUri", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetModelVersionDownloadUriArgs struct {
	Name    string `pulumi:"name"`
	Version string `pulumi:"version"`
}

type GetModelVersionDownloadUriResult struct {
	ArtifactUri string `pulumi:"artifactUri"`
}

func GetModelVersionDownloadUriOutput(ctx *pulumi.Context, args GetModelVersionDownloadUriOutputArgs, opts ...pulumi.InvokeOption) GetModelVersionDownloadUriResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetModelVersionDownloadUriResultOutput, error) {
			args := v.(GetModelVersionDownloadUriArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:getModelVersionDownloadUri", args, GetModelVersionDownloadUriResultOutput{}, options).(GetModelVersionDownloadUriResultOutput), nil
		}).(GetModelVersionDownloadUriResultOutput)
}

type GetModelVersionDownloadUriOutputArgs struct {
	Name    pulumi.StringInput `pulumi:"name"`
	Version pulumi.StringInput `pulumi:"version"`
}

func (GetModelVersionDownloadUriOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelVersionDownloadUriArgs)(nil)).Elem()
}

type GetModelVersionDownloadUriResultOutput struct{ *pulumi.OutputState }

func (GetModelVersionDownloadUriResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelVersionDownloadUriResult)(nil)).Elem()
}

func (o GetModelVersionDownloadUriResultOutput) ToGetModelVersionDownloadUriResultOutput() GetModelVersionDownloadUriResultOutput {
	return o
}

func (o GetModelVersionDownloadUriResultOutput) ToGetModelVersionDownloadUriResultOutputWithContext(ctx context.Context) GetModelVersionDownloadUriResultOutput {
	return o
}

func (o GetModelVersionDownloadUriResultOutput) ArtifactUri() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionDownloadUriResult) string { return v.ArtifactUri }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetModelVersionDownloadUriResultOutput{})
}
