// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Resolves an alias on a registered model to the model version it currently points at — useful for reading which version is, for example, `champion`.
//
// REST: `/api/2.0/mlflow/registered-models/alias` (get).
//
// ## Example Usage
func GetModelVersionByAlias(ctx *pulumi.Context, args *GetModelVersionByAliasArgs, opts ...pulumi.InvokeOption) (*GetModelVersionByAliasResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetModelVersionByAliasResult
	err := ctx.Invoke("mlflow:registry:getModelVersionByAlias", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetModelVersionByAliasArgs struct {
	Alias string `pulumi:"alias"`
	Name  string `pulumi:"name"`
}

type GetModelVersionByAliasResult struct {
	Aliases      []string          `pulumi:"aliases"`
	CurrentStage string            `pulumi:"currentStage"`
	Description  string            `pulumi:"description"`
	Name         string            `pulumi:"name"`
	RunId        string            `pulumi:"runId"`
	Source       string            `pulumi:"source"`
	Status       string            `pulumi:"status"`
	Tags         map[string]string `pulumi:"tags"`
	Version      string            `pulumi:"version"`
}

func GetModelVersionByAliasOutput(ctx *pulumi.Context, args GetModelVersionByAliasOutputArgs, opts ...pulumi.InvokeOption) GetModelVersionByAliasResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetModelVersionByAliasResultOutput, error) {
			args := v.(GetModelVersionByAliasArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:getModelVersionByAlias", args, GetModelVersionByAliasResultOutput{}, options).(GetModelVersionByAliasResultOutput), nil
		}).(GetModelVersionByAliasResultOutput)
}

type GetModelVersionByAliasOutputArgs struct {
	Alias pulumi.StringInput `pulumi:"alias"`
	Name  pulumi.StringInput `pulumi:"name"`
}

func (GetModelVersionByAliasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelVersionByAliasArgs)(nil)).Elem()
}

type GetModelVersionByAliasResultOutput struct{ *pulumi.OutputState }

func (GetModelVersionByAliasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelVersionByAliasResult)(nil)).Elem()
}

func (o GetModelVersionByAliasResultOutput) ToGetModelVersionByAliasResultOutput() GetModelVersionByAliasResultOutput {
	return o
}

func (o GetModelVersionByAliasResultOutput) ToGetModelVersionByAliasResultOutputWithContext(ctx context.Context) GetModelVersionByAliasResultOutput {
	return o
}

func (o GetModelVersionByAliasResultOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) []string { return v.Aliases }).(pulumi.StringArrayOutput)
}

func (o GetModelVersionByAliasResultOutput) CurrentStage() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.CurrentStage }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.RunId }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetModelVersionByAliasResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func (o GetModelVersionByAliasResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelVersionByAliasResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetModelVersionByAliasResultOutput{})
}
