// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up a specific model version by model name and version number.
//
// REST: `/api/2.0/mlflow/model-versions/get`.
//
// ## Example Usage
func LookupModelVersion(ctx *pulumi.Context, args *LookupModelVersionArgs, opts ...pulumi.InvokeOption) (*LookupModelVersionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupModelVersionResult
	err := ctx.Invoke("mlflow:registry:getModelVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupModelVersionArgs struct {
	Name    string `pulumi:"name"`
	Version string `pulumi:"version"`
}

type LookupModelVersionResult struct {
	Aliases      []string          `pulumi:"aliases"`
	CurrentStage string            `pulumi:"currentStage"`
	Description  string            `pulumi:"description"`
	Name         string            `pulumi:"name"`
	RunId        string            `pulumi:"runId"`
	Source       string            `pulumi:"source"`
	Status       string            `pulumi:"status"`
	Tags         map[string]string `pulumi:"tags"`
	Version      string            `pulumi:"version"`
}

func LookupModelVersionOutput(ctx *pulumi.Context, args LookupModelVersionOutputArgs, opts ...pulumi.InvokeOption) LookupModelVersionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupModelVersionResultOutput, error) {
			args := v.(LookupModelVersionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:getModelVersion", args, LookupModelVersionResultOutput{}, options).(LookupModelVersionResultOutput), nil
		}).(LookupModelVersionResultOutput)
}

type LookupModelVersionOutputArgs struct {
	Name    pulumi.StringInput `pulumi:"name"`
	Version pulumi.StringInput `pulumi:"version"`
}

func (LookupModelVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupModelVersionArgs)(nil)).Elem()
}

type LookupModelVersionResultOutput struct{ *pulumi.OutputState }

func (LookupModelVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupModelVersionResult)(nil)).Elem()
}

func (o LookupModelVersionResultOutput) ToLookupModelVersionResultOutput() LookupModelVersionResultOutput {
	return o
}

func (o LookupModelVersionResultOutput) ToLookupModelVersionResultOutputWithContext(ctx context.Context) LookupModelVersionResultOutput {
	return o
}

func (o LookupModelVersionResultOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupModelVersionResult) []string { return v.Aliases }).(pulumi.StringArrayOutput)
}

func (o LookupModelVersionResultOutput) CurrentStage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.CurrentStage }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.RunId }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupModelVersionResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupModelVersionResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func (o LookupModelVersionResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelVersionResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupModelVersionResultOutput{})
}
