// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up a registered model in the [Model Registry](https://mlflow.org/docs/latest/ml/model-registry/) by name.
//
// REST: `/api/2.0/mlflow/registered-models/get`.
//
// ## Example Usage
func LookupRegisteredModel(ctx *pulumi.Context, args *LookupRegisteredModelArgs, opts ...pulumi.InvokeOption) (*LookupRegisteredModelResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRegisteredModelResult
	err := ctx.Invoke("mlflow:registry:getRegisteredModel", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupRegisteredModelArgs struct {
	Name string `pulumi:"name"`
}

type LookupRegisteredModelResult struct {
	CreationTimestamp    int               `pulumi:"creationTimestamp"`
	Description          string            `pulumi:"description"`
	LastUpdatedTimestamp int               `pulumi:"lastUpdatedTimestamp"`
	Name                 string            `pulumi:"name"`
	Tags                 map[string]string `pulumi:"tags"`
}

func LookupRegisteredModelOutput(ctx *pulumi.Context, args LookupRegisteredModelOutputArgs, opts ...pulumi.InvokeOption) LookupRegisteredModelResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRegisteredModelResultOutput, error) {
			args := v.(LookupRegisteredModelArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:getRegisteredModel", args, LookupRegisteredModelResultOutput{}, options).(LookupRegisteredModelResultOutput), nil
		}).(LookupRegisteredModelResultOutput)
}

type LookupRegisteredModelOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupRegisteredModelOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegisteredModelArgs)(nil)).Elem()
}

type LookupRegisteredModelResultOutput struct{ *pulumi.OutputState }

func (LookupRegisteredModelResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegisteredModelResult)(nil)).Elem()
}

func (o LookupRegisteredModelResultOutput) ToLookupRegisteredModelResultOutput() LookupRegisteredModelResultOutput {
	return o
}

func (o LookupRegisteredModelResultOutput) ToLookupRegisteredModelResultOutputWithContext(ctx context.Context) LookupRegisteredModelResultOutput {
	return o
}

func (o LookupRegisteredModelResultOutput) CreationTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRegisteredModelResult) int { return v.CreationTimestamp }).(pulumi.IntOutput)
}

func (o LookupRegisteredModelResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRegisteredModelResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupRegisteredModelResultOutput) LastUpdatedTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v LookupRegisteredModelResult) int { return v.LastUpdatedTimestamp }).(pulumi.IntOutput)
}

func (o LookupRegisteredModelResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRegisteredModelResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupRegisteredModelResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupRegisteredModelResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRegisteredModelResultOutput{})
}
