// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"fmt"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "mlflow:registry:ModelVersion":
		r = &ModelVersion{}
	case "mlflow:registry:RegisteredModel":
		r = &RegisteredModel{}
	case "mlflow:registry:RegisteredModelAlias":
		r = &RegisteredModelAlias{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"mlflow",
		"registry",
		&module{version},
	)
}
