// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a version of a [registered model](https://mlflow.org/docs/latest/ml/model-registry/) — an immutable snapshot of a model's artifacts.
//
// The `source`, `runId` and `runLink` are set once: changing any of them replaces the version. Only `description` and `tags` update in place. On create, the provider waits until the version's status is `READY`.
//
// > **Note:** `stage` (None/Staging/Production/Archived) is **deprecated in MLflow 3**. Prefer [`RegisteredModelAlias`](/registry/registeredmodelalias) to drive deployments. Setting `stage` against a 3.x server emits a warning.
//
// REST endpoints: `/api/2.0/mlflow/model-versions/{create,get,update,delete,set-tag,delete-tag,transition-stage}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-modelversion).
//
// ## Example Usage
//
// ## Import
//
// Model versions can be imported using `<model-name>/<version>`:
//
// ```sh
// pulumi import mlflow:registry:ModelVersion fraud-v1 fraud-detector/1
// ```
type ModelVersion struct {
	pulumi.CustomResourceState

	// Aliases currently pointing at this version.
	Aliases pulumi.StringArrayOutput `pulumi:"aliases"`
	// Creation time, in epoch milliseconds.
	CreationTimestamp pulumi.IntOutput `pulumi:"creationTimestamp"`
	// The version's current stage (deprecated in MLflow 3; prefer aliases).
	CurrentStage pulumi.StringOutput `pulumi:"currentStage"`
	// Optional human-readable description. Updated in place.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Last update time, in epoch milliseconds.
	LastUpdatedTimestamp pulumi.IntOutput `pulumi:"lastUpdatedTimestamp"`
	// Parent registered model name. Changing it replaces the version.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optional MLflow run that produced the model. Changing it replaces the version.
	RunId pulumi.StringPtrOutput `pulumi:"runId"`
	// Optional link to the source run. Changing it replaces the version.
	RunLink pulumi.StringPtrOutput `pulumi:"runLink"`
	// URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
	Source pulumi.StringOutput `pulumi:"source"`
	// Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
	//
	// Deprecated: Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
	Stage pulumi.StringPtrOutput `pulumi:"stage"`
	// Registration status; the provider waits for READY on create.
	Status pulumi.StringOutput `pulumi:"status"`
	// Optional key/value metadata tags. Synced in place.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// Server-assigned version number (immutable).
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewModelVersion registers a new resource with the given unique name, arguments, and options.
func NewModelVersion(ctx *pulumi.Context,
	name string, args *ModelVersionArgs, opts ...pulumi.ResourceOption) (*ModelVersion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"name",
		"runId",
		"runLink",
		"source",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ModelVersion
	err := ctx.RegisterResource("mlflow:registry:ModelVersion", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetModelVersion gets an existing ModelVersion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetModelVersion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ModelVersionState, opts ...pulumi.ResourceOption) (*ModelVersion, error) {
	var resource ModelVersion
	err := ctx.ReadResource("mlflow:registry:ModelVersion", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ModelVersion resources.
type modelVersionState struct {
}

type ModelVersionState struct {
}

func (ModelVersionState) ElementType() reflect.Type {
	return reflect.TypeOf((*modelVersionState)(nil)).Elem()
}

type modelVersionArgs struct {
	// Optional human-readable description. Updated in place.
	Description *string `pulumi:"description"`
	// Parent registered model name. Changing it replaces the version.
	Name string `pulumi:"name"`
	// Optional MLflow run that produced the model. Changing it replaces the version.
	RunId *string `pulumi:"runId"`
	// Optional link to the source run. Changing it replaces the version.
	RunLink *string `pulumi:"runLink"`
	// URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
	Source string `pulumi:"source"`
	// Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
	//
	// Deprecated: Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
	Stage *string `pulumi:"stage"`
	// Optional key/value metadata tags. Synced in place.
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a ModelVersion resource.
type ModelVersionArgs struct {
	// Optional human-readable description. Updated in place.
	Description pulumi.StringPtrInput
	// Parent registered model name. Changing it replaces the version.
	Name pulumi.StringInput
	// Optional MLflow run that produced the model. Changing it replaces the version.
	RunId pulumi.StringPtrInput
	// Optional link to the source run. Changing it replaces the version.
	RunLink pulumi.StringPtrInput
	// URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
	Source pulumi.StringInput
	// Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
	//
	// Deprecated: Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
	Stage pulumi.StringPtrInput
	// Optional key/value metadata tags. Synced in place.
	Tags pulumi.StringMapInput
}

func (ModelVersionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*modelVersionArgs)(nil)).Elem()
}

type ModelVersionInput interface {
	pulumi.Input

	ToModelVersionOutput() ModelVersionOutput
	ToModelVersionOutputWithContext(ctx context.Context) ModelVersionOutput
}

func (*ModelVersion) ElementType() reflect.Type {
	return reflect.TypeOf((**ModelVersion)(nil)).Elem()
}

func (i *ModelVersion) ToModelVersionOutput() ModelVersionOutput {
	return i.ToModelVersionOutputWithContext(context.Background())
}

func (i *ModelVersion) ToModelVersionOutputWithContext(ctx context.Context) ModelVersionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ModelVersionOutput)
}

// ModelVersionArrayInput is an input type that accepts ModelVersionArray and ModelVersionArrayOutput values.
// You can construct a concrete instance of `ModelVersionArrayInput` via:
//
//	ModelVersionArray{ ModelVersionArgs{...} }
type ModelVersionArrayInput interface {
	pulumi.Input

	ToModelVersionArrayOutput() ModelVersionArrayOutput
	ToModelVersionArrayOutputWithContext(context.Context) ModelVersionArrayOutput
}

type ModelVersionArray []ModelVersionInput

func (ModelVersionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ModelVersion)(nil)).Elem()
}

func (i ModelVersionArray) ToModelVersionArrayOutput() ModelVersionArrayOutput {
	return i.ToModelVersionArrayOutputWithContext(context.Background())
}

func (i ModelVersionArray) ToModelVersionArrayOutputWithContext(ctx context.Context) ModelVersionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ModelVersionArrayOutput)
}

// ModelVersionMapInput is an input type that accepts ModelVersionMap and ModelVersionMapOutput values.
// You can construct a concrete instance of `ModelVersionMapInput` via:
//
//	ModelVersionMap{ "key": ModelVersionArgs{...} }
type ModelVersionMapInput interface {
	pulumi.Input

	ToModelVersionMapOutput() ModelVersionMapOutput
	ToModelVersionMapOutputWithContext(context.Context) ModelVersionMapOutput
}

type ModelVersionMap map[string]ModelVersionInput

func (ModelVersionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ModelVersion)(nil)).Elem()
}

func (i ModelVersionMap) ToModelVersionMapOutput() ModelVersionMapOutput {
	return i.ToModelVersionMapOutputWithContext(context.Background())
}

func (i ModelVersionMap) ToModelVersionMapOutputWithContext(ctx context.Context) ModelVersionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ModelVersionMapOutput)
}

type ModelVersionOutput struct{ *pulumi.OutputState }

func (ModelVersionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ModelVersion)(nil)).Elem()
}

func (o ModelVersionOutput) ToModelVersionOutput() ModelVersionOutput {
	return o
}

func (o ModelVersionOutput) ToModelVersionOutputWithContext(ctx context.Context) ModelVersionOutput {
	return o
}

// Aliases currently pointing at this version.
func (o ModelVersionOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringArrayOutput { return v.Aliases }).(pulumi.StringArrayOutput)
}

// Creation time, in epoch milliseconds.
func (o ModelVersionOutput) CreationTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.IntOutput { return v.CreationTimestamp }).(pulumi.IntOutput)
}

// The version's current stage (deprecated in MLflow 3; prefer aliases).
func (o ModelVersionOutput) CurrentStage() pulumi.StringOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringOutput { return v.CurrentStage }).(pulumi.StringOutput)
}

// Optional human-readable description. Updated in place.
func (o ModelVersionOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Last update time, in epoch milliseconds.
func (o ModelVersionOutput) LastUpdatedTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.IntOutput { return v.LastUpdatedTimestamp }).(pulumi.IntOutput)
}

// Parent registered model name. Changing it replaces the version.
func (o ModelVersionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional MLflow run that produced the model. Changing it replaces the version.
func (o ModelVersionOutput) RunId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringPtrOutput { return v.RunId }).(pulumi.StringPtrOutput)
}

// Optional link to the source run. Changing it replaces the version.
func (o ModelVersionOutput) RunLink() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringPtrOutput { return v.RunLink }).(pulumi.StringPtrOutput)
}

// URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
func (o ModelVersionOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
//
// Deprecated: Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
func (o ModelVersionOutput) Stage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringPtrOutput { return v.Stage }).(pulumi.StringPtrOutput)
}

// Registration status; the provider waits for READY on create.
func (o ModelVersionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Optional key/value metadata tags. Synced in place.
func (o ModelVersionOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// Server-assigned version number (immutable).
func (o ModelVersionOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *ModelVersion) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type ModelVersionArrayOutput struct{ *pulumi.OutputState }

func (ModelVersionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ModelVersion)(nil)).Elem()
}

func (o ModelVersionArrayOutput) ToModelVersionArrayOutput() ModelVersionArrayOutput {
	return o
}

func (o ModelVersionArrayOutput) ToModelVersionArrayOutputWithContext(ctx context.Context) ModelVersionArrayOutput {
	return o
}

func (o ModelVersionArrayOutput) Index(i pulumi.IntInput) ModelVersionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ModelVersion {
		return vs[0].([]*ModelVersion)[vs[1].(int)]
	}).(ModelVersionOutput)
}

type ModelVersionMapOutput struct{ *pulumi.OutputState }

func (ModelVersionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ModelVersion)(nil)).Elem()
}

func (o ModelVersionMapOutput) ToModelVersionMapOutput() ModelVersionMapOutput {
	return o
}

func (o ModelVersionMapOutput) ToModelVersionMapOutputWithContext(ctx context.Context) ModelVersionMapOutput {
	return o
}

func (o ModelVersionMapOutput) MapIndex(k pulumi.StringInput) ModelVersionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ModelVersion {
		return vs[0].(map[string]*ModelVersion)[vs[1].(string)]
	}).(ModelVersionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ModelVersionInput)(nil)).Elem(), &ModelVersion{})
	pulumi.RegisterInputType(reflect.TypeOf((*ModelVersionArrayInput)(nil)).Elem(), ModelVersionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ModelVersionMapInput)(nil)).Elem(), ModelVersionMap{})
	pulumi.RegisterOutputType(ModelVersionOutput{})
	pulumi.RegisterOutputType(ModelVersionArrayOutput{})
	pulumi.RegisterOutputType(ModelVersionMapOutput{})
}
