// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ModelVersionResult struct {
	Aliases      []string          `pulumi:"aliases"`
	CurrentStage string            `pulumi:"currentStage"`
	Description  string            `pulumi:"description"`
	Name         string            `pulumi:"name"`
	RunId        string            `pulumi:"runId"`
	Source       string            `pulumi:"source"`
	Status       string            `pulumi:"status"`
	Tags         map[string]string `pulumi:"tags"`
	Version      string            `pulumi:"version"`
}

type ModelVersionResultOutput struct{ *pulumi.OutputState }

func (ModelVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ModelVersionResult)(nil)).Elem()
}

func (o ModelVersionResultOutput) ToModelVersionResultOutput() ModelVersionResultOutput {
	return o
}

func (o ModelVersionResultOutput) ToModelVersionResultOutputWithContext(ctx context.Context) ModelVersionResultOutput {
	return o
}

func (o ModelVersionResultOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ModelVersionResult) []string { return v.Aliases }).(pulumi.StringArrayOutput)
}

func (o ModelVersionResultOutput) CurrentStage() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.CurrentStage }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.RunId }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o ModelVersionResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v ModelVersionResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func (o ModelVersionResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v ModelVersionResult) string { return v.Version }).(pulumi.StringOutput)
}

type ModelVersionResultArrayOutput struct{ *pulumi.OutputState }

func (ModelVersionResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ModelVersionResult)(nil)).Elem()
}

func (o ModelVersionResultArrayOutput) ToModelVersionResultArrayOutput() ModelVersionResultArrayOutput {
	return o
}

func (o ModelVersionResultArrayOutput) ToModelVersionResultArrayOutputWithContext(ctx context.Context) ModelVersionResultArrayOutput {
	return o
}

func (o ModelVersionResultArrayOutput) Index(i pulumi.IntInput) ModelVersionResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ModelVersionResult {
		return vs[0].([]ModelVersionResult)[vs[1].(int)]
	}).(ModelVersionResultOutput)
}

type RegisteredModelResult struct {
	CreationTimestamp    int               `pulumi:"creationTimestamp"`
	Description          string            `pulumi:"description"`
	LastUpdatedTimestamp int               `pulumi:"lastUpdatedTimestamp"`
	Name                 string            `pulumi:"name"`
	Tags                 map[string]string `pulumi:"tags"`
}

type RegisteredModelResultOutput struct{ *pulumi.OutputState }

func (RegisteredModelResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RegisteredModelResult)(nil)).Elem()
}

func (o RegisteredModelResultOutput) ToRegisteredModelResultOutput() RegisteredModelResultOutput {
	return o
}

func (o RegisteredModelResultOutput) ToRegisteredModelResultOutputWithContext(ctx context.Context) RegisteredModelResultOutput {
	return o
}

func (o RegisteredModelResultOutput) CreationTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v RegisteredModelResult) int { return v.CreationTimestamp }).(pulumi.IntOutput)
}

func (o RegisteredModelResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v RegisteredModelResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o RegisteredModelResultOutput) LastUpdatedTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v RegisteredModelResult) int { return v.LastUpdatedTimestamp }).(pulumi.IntOutput)
}

func (o RegisteredModelResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v RegisteredModelResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o RegisteredModelResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v RegisteredModelResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

type RegisteredModelResultArrayOutput struct{ *pulumi.OutputState }

func (RegisteredModelResultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RegisteredModelResult)(nil)).Elem()
}

func (o RegisteredModelResultArrayOutput) ToRegisteredModelResultArrayOutput() RegisteredModelResultArrayOutput {
	return o
}

func (o RegisteredModelResultArrayOutput) ToRegisteredModelResultArrayOutputWithContext(ctx context.Context) RegisteredModelResultArrayOutput {
	return o
}

func (o RegisteredModelResultArrayOutput) Index(i pulumi.IntInput) RegisteredModelResultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RegisteredModelResult {
		return vs[0].([]RegisteredModelResult)[vs[1].(int)]
	}).(RegisteredModelResultOutput)
}

func init() {
	pulumi.RegisterOutputType(ModelVersionResultOutput{})
	pulumi.RegisterOutputType(ModelVersionResultArrayOutput{})
	pulumi.RegisterOutputType(RegisteredModelResultOutput{})
	pulumi.RegisterOutputType(RegisteredModelResultArrayOutput{})
}
