// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a single key/value tag on a registered model that is owned elsewhere (e.g. created by a training pipeline). Unlike the `tags` map on RegisteredModel it does not own the model: it sets the tag on create, updates the value in place, and removes only that tag on delete. This mirrors the `aws.ec2.Tag`-style pattern for managing one attribute of an externally-owned resource. Backed by the MLflow `registered-models/set-tag` and `registered-models/delete-tag` endpoints.
//
// ## Example Usage
//
// ## Import
//
// ```sh
// pulumi import mlflow:registry:RegisteredModelTag serving-host <modelName>/<key>
// ```
type RegisteredModelTag struct {
	pulumi.CustomResourceState

	Key   pulumi.StringOutput `pulumi:"key"`
	Name  pulumi.StringOutput `pulumi:"name"`
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewRegisteredModelTag registers a new resource with the given unique name, arguments, and options.
func NewRegisteredModelTag(ctx *pulumi.Context,
	name string, args *RegisteredModelTagArgs, opts ...pulumi.ResourceOption) (*RegisteredModelTag, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"key",
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RegisteredModelTag
	err := ctx.RegisterResource("mlflow:registry:RegisteredModelTag", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegisteredModelTag gets an existing RegisteredModelTag resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegisteredModelTag(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegisteredModelTagState, opts ...pulumi.ResourceOption) (*RegisteredModelTag, error) {
	var resource RegisteredModelTag
	err := ctx.ReadResource("mlflow:registry:RegisteredModelTag", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RegisteredModelTag resources.
type registeredModelTagState struct {
}

type RegisteredModelTagState struct {
}

func (RegisteredModelTagState) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelTagState)(nil)).Elem()
}

type registeredModelTagArgs struct {
	Key   string `pulumi:"key"`
	Name  string `pulumi:"name"`
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a RegisteredModelTag resource.
type RegisteredModelTagArgs struct {
	Key   pulumi.StringInput
	Name  pulumi.StringInput
	Value pulumi.StringInput
}

func (RegisteredModelTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelTagArgs)(nil)).Elem()
}

type RegisteredModelTagInput interface {
	pulumi.Input

	ToRegisteredModelTagOutput() RegisteredModelTagOutput
	ToRegisteredModelTagOutputWithContext(ctx context.Context) RegisteredModelTagOutput
}

func (*RegisteredModelTag) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelTag)(nil)).Elem()
}

func (i *RegisteredModelTag) ToRegisteredModelTagOutput() RegisteredModelTagOutput {
	return i.ToRegisteredModelTagOutputWithContext(context.Background())
}

func (i *RegisteredModelTag) ToRegisteredModelTagOutputWithContext(ctx context.Context) RegisteredModelTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelTagOutput)
}

// RegisteredModelTagArrayInput is an input type that accepts RegisteredModelTagArray and RegisteredModelTagArrayOutput values.
// You can construct a concrete instance of `RegisteredModelTagArrayInput` via:
//
//	RegisteredModelTagArray{ RegisteredModelTagArgs{...} }
type RegisteredModelTagArrayInput interface {
	pulumi.Input

	ToRegisteredModelTagArrayOutput() RegisteredModelTagArrayOutput
	ToRegisteredModelTagArrayOutputWithContext(context.Context) RegisteredModelTagArrayOutput
}

type RegisteredModelTagArray []RegisteredModelTagInput

func (RegisteredModelTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelTag)(nil)).Elem()
}

func (i RegisteredModelTagArray) ToRegisteredModelTagArrayOutput() RegisteredModelTagArrayOutput {
	return i.ToRegisteredModelTagArrayOutputWithContext(context.Background())
}

func (i RegisteredModelTagArray) ToRegisteredModelTagArrayOutputWithContext(ctx context.Context) RegisteredModelTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelTagArrayOutput)
}

// RegisteredModelTagMapInput is an input type that accepts RegisteredModelTagMap and RegisteredModelTagMapOutput values.
// You can construct a concrete instance of `RegisteredModelTagMapInput` via:
//
//	RegisteredModelTagMap{ "key": RegisteredModelTagArgs{...} }
type RegisteredModelTagMapInput interface {
	pulumi.Input

	ToRegisteredModelTagMapOutput() RegisteredModelTagMapOutput
	ToRegisteredModelTagMapOutputWithContext(context.Context) RegisteredModelTagMapOutput
}

type RegisteredModelTagMap map[string]RegisteredModelTagInput

func (RegisteredModelTagMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelTag)(nil)).Elem()
}

func (i RegisteredModelTagMap) ToRegisteredModelTagMapOutput() RegisteredModelTagMapOutput {
	return i.ToRegisteredModelTagMapOutputWithContext(context.Background())
}

func (i RegisteredModelTagMap) ToRegisteredModelTagMapOutputWithContext(ctx context.Context) RegisteredModelTagMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelTagMapOutput)
}

type RegisteredModelTagOutput struct{ *pulumi.OutputState }

func (RegisteredModelTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelTag)(nil)).Elem()
}

func (o RegisteredModelTagOutput) ToRegisteredModelTagOutput() RegisteredModelTagOutput {
	return o
}

func (o RegisteredModelTagOutput) ToRegisteredModelTagOutputWithContext(ctx context.Context) RegisteredModelTagOutput {
	return o
}

func (o RegisteredModelTagOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelTag) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

func (o RegisteredModelTagOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelTag) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o RegisteredModelTagOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelTag) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

type RegisteredModelTagArrayOutput struct{ *pulumi.OutputState }

func (RegisteredModelTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelTag)(nil)).Elem()
}

func (o RegisteredModelTagArrayOutput) ToRegisteredModelTagArrayOutput() RegisteredModelTagArrayOutput {
	return o
}

func (o RegisteredModelTagArrayOutput) ToRegisteredModelTagArrayOutputWithContext(ctx context.Context) RegisteredModelTagArrayOutput {
	return o
}

func (o RegisteredModelTagArrayOutput) Index(i pulumi.IntInput) RegisteredModelTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RegisteredModelTag {
		return vs[0].([]*RegisteredModelTag)[vs[1].(int)]
	}).(RegisteredModelTagOutput)
}

type RegisteredModelTagMapOutput struct{ *pulumi.OutputState }

func (RegisteredModelTagMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelTag)(nil)).Elem()
}

func (o RegisteredModelTagMapOutput) ToRegisteredModelTagMapOutput() RegisteredModelTagMapOutput {
	return o
}

func (o RegisteredModelTagMapOutput) ToRegisteredModelTagMapOutputWithContext(ctx context.Context) RegisteredModelTagMapOutput {
	return o
}

func (o RegisteredModelTagMapOutput) MapIndex(k pulumi.StringInput) RegisteredModelTagOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RegisteredModelTag {
		return vs[0].(map[string]*RegisteredModelTag)[vs[1].(string)]
	}).(RegisteredModelTagOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelTagInput)(nil)).Elem(), &RegisteredModelTag{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelTagArrayInput)(nil)).Elem(), RegisteredModelTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelTagMapInput)(nil)).Elem(), RegisteredModelTagMap{})
	pulumi.RegisterOutputType(RegisteredModelTagOutput{})
	pulumi.RegisterOutputType(RegisteredModelTagArrayOutput{})
	pulumi.RegisterOutputType(RegisteredModelTagMapOutput{})
}
