// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a model in the [MLflow Model Registry](https://mlflow.org/docs/latest/ml/model-registry/) — a named container that groups the versions of a model.
//
// The model `name` is the resource identity; changing it replaces the resource. Only `description` and `tags` are updated in place.
//
// REST endpoints: `/api/2.0/mlflow/registered-models/{create,get,update,delete,set-tag,delete-tag}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-registeredmodel).
//
// ## Example Usage
//
// ## Import
//
// Registered models can be imported using the model name:
//
// ```sh
// pulumi import mlflow:registry:RegisteredModel fraud fraud-detector
// ```
type RegisteredModel struct {
	pulumi.CustomResourceState

	// Model creation time, in epoch milliseconds.
	CreationTimestamp pulumi.IntOutput `pulumi:"creationTimestamp"`
	// Optional human-readable description. Updated in place.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Last update time, in epoch milliseconds.
	LastUpdatedTimestamp pulumi.IntOutput `pulumi:"lastUpdatedTimestamp"`
	// Unique name of the registered model. This is the resource identity; changing it replaces the resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
}

// NewRegisteredModel registers a new resource with the given unique name, arguments, and options.
func NewRegisteredModel(ctx *pulumi.Context,
	name string, args *RegisteredModelArgs, opts ...pulumi.ResourceOption) (*RegisteredModel, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RegisteredModel
	err := ctx.RegisterResource("mlflow:registry:RegisteredModel", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegisteredModel gets an existing RegisteredModel resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegisteredModel(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegisteredModelState, opts ...pulumi.ResourceOption) (*RegisteredModel, error) {
	var resource RegisteredModel
	err := ctx.ReadResource("mlflow:registry:RegisteredModel", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RegisteredModel resources.
type registeredModelState struct {
}

type RegisteredModelState struct {
}

func (RegisteredModelState) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelState)(nil)).Elem()
}

type registeredModelArgs struct {
	// Optional human-readable description. Updated in place.
	Description *string `pulumi:"description"`
	// Unique name of the registered model. This is the resource identity; changing it replaces the resource.
	Name string `pulumi:"name"`
	// Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a RegisteredModel resource.
type RegisteredModelArgs struct {
	// Optional human-readable description. Updated in place.
	Description pulumi.StringPtrInput
	// Unique name of the registered model. This is the resource identity; changing it replaces the resource.
	Name pulumi.StringInput
	// Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
	Tags pulumi.StringMapInput
}

func (RegisteredModelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelArgs)(nil)).Elem()
}

type RegisteredModelInput interface {
	pulumi.Input

	ToRegisteredModelOutput() RegisteredModelOutput
	ToRegisteredModelOutputWithContext(ctx context.Context) RegisteredModelOutput
}

func (*RegisteredModel) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModel)(nil)).Elem()
}

func (i *RegisteredModel) ToRegisteredModelOutput() RegisteredModelOutput {
	return i.ToRegisteredModelOutputWithContext(context.Background())
}

func (i *RegisteredModel) ToRegisteredModelOutputWithContext(ctx context.Context) RegisteredModelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelOutput)
}

// RegisteredModelArrayInput is an input type that accepts RegisteredModelArray and RegisteredModelArrayOutput values.
// You can construct a concrete instance of `RegisteredModelArrayInput` via:
//
//	RegisteredModelArray{ RegisteredModelArgs{...} }
type RegisteredModelArrayInput interface {
	pulumi.Input

	ToRegisteredModelArrayOutput() RegisteredModelArrayOutput
	ToRegisteredModelArrayOutputWithContext(context.Context) RegisteredModelArrayOutput
}

type RegisteredModelArray []RegisteredModelInput

func (RegisteredModelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModel)(nil)).Elem()
}

func (i RegisteredModelArray) ToRegisteredModelArrayOutput() RegisteredModelArrayOutput {
	return i.ToRegisteredModelArrayOutputWithContext(context.Background())
}

func (i RegisteredModelArray) ToRegisteredModelArrayOutputWithContext(ctx context.Context) RegisteredModelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelArrayOutput)
}

// RegisteredModelMapInput is an input type that accepts RegisteredModelMap and RegisteredModelMapOutput values.
// You can construct a concrete instance of `RegisteredModelMapInput` via:
//
//	RegisteredModelMap{ "key": RegisteredModelArgs{...} }
type RegisteredModelMapInput interface {
	pulumi.Input

	ToRegisteredModelMapOutput() RegisteredModelMapOutput
	ToRegisteredModelMapOutputWithContext(context.Context) RegisteredModelMapOutput
}

type RegisteredModelMap map[string]RegisteredModelInput

func (RegisteredModelMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModel)(nil)).Elem()
}

func (i RegisteredModelMap) ToRegisteredModelMapOutput() RegisteredModelMapOutput {
	return i.ToRegisteredModelMapOutputWithContext(context.Background())
}

func (i RegisteredModelMap) ToRegisteredModelMapOutputWithContext(ctx context.Context) RegisteredModelMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelMapOutput)
}

type RegisteredModelOutput struct{ *pulumi.OutputState }

func (RegisteredModelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModel)(nil)).Elem()
}

func (o RegisteredModelOutput) ToRegisteredModelOutput() RegisteredModelOutput {
	return o
}

func (o RegisteredModelOutput) ToRegisteredModelOutputWithContext(ctx context.Context) RegisteredModelOutput {
	return o
}

// Model creation time, in epoch milliseconds.
func (o RegisteredModelOutput) CreationTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v *RegisteredModel) pulumi.IntOutput { return v.CreationTimestamp }).(pulumi.IntOutput)
}

// Optional human-readable description. Updated in place.
func (o RegisteredModelOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RegisteredModel) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Last update time, in epoch milliseconds.
func (o RegisteredModelOutput) LastUpdatedTimestamp() pulumi.IntOutput {
	return o.ApplyT(func(v *RegisteredModel) pulumi.IntOutput { return v.LastUpdatedTimestamp }).(pulumi.IntOutput)
}

// Unique name of the registered model. This is the resource identity; changing it replaces the resource.
func (o RegisteredModelOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModel) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
func (o RegisteredModelOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *RegisteredModel) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

type RegisteredModelArrayOutput struct{ *pulumi.OutputState }

func (RegisteredModelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModel)(nil)).Elem()
}

func (o RegisteredModelArrayOutput) ToRegisteredModelArrayOutput() RegisteredModelArrayOutput {
	return o
}

func (o RegisteredModelArrayOutput) ToRegisteredModelArrayOutputWithContext(ctx context.Context) RegisteredModelArrayOutput {
	return o
}

func (o RegisteredModelArrayOutput) Index(i pulumi.IntInput) RegisteredModelOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RegisteredModel {
		return vs[0].([]*RegisteredModel)[vs[1].(int)]
	}).(RegisteredModelOutput)
}

type RegisteredModelMapOutput struct{ *pulumi.OutputState }

func (RegisteredModelMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModel)(nil)).Elem()
}

func (o RegisteredModelMapOutput) ToRegisteredModelMapOutput() RegisteredModelMapOutput {
	return o
}

func (o RegisteredModelMapOutput) ToRegisteredModelMapOutputWithContext(ctx context.Context) RegisteredModelMapOutput {
	return o
}

func (o RegisteredModelMapOutput) MapIndex(k pulumi.StringInput) RegisteredModelOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RegisteredModel {
		return vs[0].(map[string]*RegisteredModel)[vs[1].(string)]
	}).(RegisteredModelOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelInput)(nil)).Elem(), &RegisteredModel{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelArrayInput)(nil)).Elem(), RegisteredModelArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelMapInput)(nil)).Elem(), RegisteredModelMap{})
	pulumi.RegisterOutputType(RegisteredModelOutput{})
	pulumi.RegisterOutputType(RegisteredModelArrayOutput{})
	pulumi.RegisterOutputType(RegisteredModelMapOutput{})
}
