// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a named [alias](https://mlflow.org/docs/latest/ml/model-registry/#deploy-and-organize-models-with-aliases-and-tags) on a registered model that points at a specific version (for example `champion` → version 3).
//
// Aliases are mutable pointers and are the **recommended** way to drive deployments; they supersede the deprecated model *stages*. `version` is updatable — changing it re-points the alias to a different version — while `modelName` and `alias` changes replace the resource.
//
// REST endpoints: `/api/2.0/mlflow/registered-models/alias` (set/delete/get) — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#set-registered-model-alias).
//
// ## Example Usage
//
// ## Import
//
// Aliases can be imported using `<model-name>/<alias>`:
//
// ```sh
// pulumi import mlflow:registry:RegisteredModelAlias champion fraud-detector/champion
// ```
type RegisteredModelAlias struct {
	pulumi.CustomResourceState

	// Alias name, e.g. "champion". Changing it replaces the resource.
	Alias pulumi.StringOutput `pulumi:"alias"`
	// Registered model the alias belongs to. Changing it replaces the resource.
	ModelName pulumi.StringOutput `pulumi:"modelName"`
	// Model version the alias points at. Updating it re-points the alias in place.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewRegisteredModelAlias registers a new resource with the given unique name, arguments, and options.
func NewRegisteredModelAlias(ctx *pulumi.Context,
	name string, args *RegisteredModelAliasArgs, opts ...pulumi.ResourceOption) (*RegisteredModelAlias, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Alias == nil {
		return nil, errors.New("invalid value for required argument 'Alias'")
	}
	if args.ModelName == nil {
		return nil, errors.New("invalid value for required argument 'ModelName'")
	}
	if args.Version == nil {
		return nil, errors.New("invalid value for required argument 'Version'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"alias",
		"modelName",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RegisteredModelAlias
	err := ctx.RegisterResource("mlflow:registry:RegisteredModelAlias", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegisteredModelAlias gets an existing RegisteredModelAlias resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegisteredModelAlias(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegisteredModelAliasState, opts ...pulumi.ResourceOption) (*RegisteredModelAlias, error) {
	var resource RegisteredModelAlias
	err := ctx.ReadResource("mlflow:registry:RegisteredModelAlias", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RegisteredModelAlias resources.
type registeredModelAliasState struct {
}

type RegisteredModelAliasState struct {
}

func (RegisteredModelAliasState) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelAliasState)(nil)).Elem()
}

type registeredModelAliasArgs struct {
	// Alias name, e.g. "champion". Changing it replaces the resource.
	Alias string `pulumi:"alias"`
	// Registered model the alias belongs to. Changing it replaces the resource.
	ModelName string `pulumi:"modelName"`
	// Model version the alias points at. Updating it re-points the alias in place.
	Version string `pulumi:"version"`
}

// The set of arguments for constructing a RegisteredModelAlias resource.
type RegisteredModelAliasArgs struct {
	// Alias name, e.g. "champion". Changing it replaces the resource.
	Alias pulumi.StringInput
	// Registered model the alias belongs to. Changing it replaces the resource.
	ModelName pulumi.StringInput
	// Model version the alias points at. Updating it re-points the alias in place.
	Version pulumi.StringInput
}

func (RegisteredModelAliasArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelAliasArgs)(nil)).Elem()
}

type RegisteredModelAliasInput interface {
	pulumi.Input

	ToRegisteredModelAliasOutput() RegisteredModelAliasOutput
	ToRegisteredModelAliasOutputWithContext(ctx context.Context) RegisteredModelAliasOutput
}

func (*RegisteredModelAlias) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelAlias)(nil)).Elem()
}

func (i *RegisteredModelAlias) ToRegisteredModelAliasOutput() RegisteredModelAliasOutput {
	return i.ToRegisteredModelAliasOutputWithContext(context.Background())
}

func (i *RegisteredModelAlias) ToRegisteredModelAliasOutputWithContext(ctx context.Context) RegisteredModelAliasOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelAliasOutput)
}

// RegisteredModelAliasArrayInput is an input type that accepts RegisteredModelAliasArray and RegisteredModelAliasArrayOutput values.
// You can construct a concrete instance of `RegisteredModelAliasArrayInput` via:
//
//	RegisteredModelAliasArray{ RegisteredModelAliasArgs{...} }
type RegisteredModelAliasArrayInput interface {
	pulumi.Input

	ToRegisteredModelAliasArrayOutput() RegisteredModelAliasArrayOutput
	ToRegisteredModelAliasArrayOutputWithContext(context.Context) RegisteredModelAliasArrayOutput
}

type RegisteredModelAliasArray []RegisteredModelAliasInput

func (RegisteredModelAliasArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelAlias)(nil)).Elem()
}

func (i RegisteredModelAliasArray) ToRegisteredModelAliasArrayOutput() RegisteredModelAliasArrayOutput {
	return i.ToRegisteredModelAliasArrayOutputWithContext(context.Background())
}

func (i RegisteredModelAliasArray) ToRegisteredModelAliasArrayOutputWithContext(ctx context.Context) RegisteredModelAliasArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelAliasArrayOutput)
}

// RegisteredModelAliasMapInput is an input type that accepts RegisteredModelAliasMap and RegisteredModelAliasMapOutput values.
// You can construct a concrete instance of `RegisteredModelAliasMapInput` via:
//
//	RegisteredModelAliasMap{ "key": RegisteredModelAliasArgs{...} }
type RegisteredModelAliasMapInput interface {
	pulumi.Input

	ToRegisteredModelAliasMapOutput() RegisteredModelAliasMapOutput
	ToRegisteredModelAliasMapOutputWithContext(context.Context) RegisteredModelAliasMapOutput
}

type RegisteredModelAliasMap map[string]RegisteredModelAliasInput

func (RegisteredModelAliasMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelAlias)(nil)).Elem()
}

func (i RegisteredModelAliasMap) ToRegisteredModelAliasMapOutput() RegisteredModelAliasMapOutput {
	return i.ToRegisteredModelAliasMapOutputWithContext(context.Background())
}

func (i RegisteredModelAliasMap) ToRegisteredModelAliasMapOutputWithContext(ctx context.Context) RegisteredModelAliasMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelAliasMapOutput)
}

type RegisteredModelAliasOutput struct{ *pulumi.OutputState }

func (RegisteredModelAliasOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelAlias)(nil)).Elem()
}

func (o RegisteredModelAliasOutput) ToRegisteredModelAliasOutput() RegisteredModelAliasOutput {
	return o
}

func (o RegisteredModelAliasOutput) ToRegisteredModelAliasOutputWithContext(ctx context.Context) RegisteredModelAliasOutput {
	return o
}

// Alias name, e.g. "champion". Changing it replaces the resource.
func (o RegisteredModelAliasOutput) Alias() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelAlias) pulumi.StringOutput { return v.Alias }).(pulumi.StringOutput)
}

// Registered model the alias belongs to. Changing it replaces the resource.
func (o RegisteredModelAliasOutput) ModelName() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelAlias) pulumi.StringOutput { return v.ModelName }).(pulumi.StringOutput)
}

// Model version the alias points at. Updating it re-points the alias in place.
func (o RegisteredModelAliasOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelAlias) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type RegisteredModelAliasArrayOutput struct{ *pulumi.OutputState }

func (RegisteredModelAliasArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelAlias)(nil)).Elem()
}

func (o RegisteredModelAliasArrayOutput) ToRegisteredModelAliasArrayOutput() RegisteredModelAliasArrayOutput {
	return o
}

func (o RegisteredModelAliasArrayOutput) ToRegisteredModelAliasArrayOutputWithContext(ctx context.Context) RegisteredModelAliasArrayOutput {
	return o
}

func (o RegisteredModelAliasArrayOutput) Index(i pulumi.IntInput) RegisteredModelAliasOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RegisteredModelAlias {
		return vs[0].([]*RegisteredModelAlias)[vs[1].(int)]
	}).(RegisteredModelAliasOutput)
}

type RegisteredModelAliasMapOutput struct{ *pulumi.OutputState }

func (RegisteredModelAliasMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelAlias)(nil)).Elem()
}

func (o RegisteredModelAliasMapOutput) ToRegisteredModelAliasMapOutput() RegisteredModelAliasMapOutput {
	return o
}

func (o RegisteredModelAliasMapOutput) ToRegisteredModelAliasMapOutputWithContext(ctx context.Context) RegisteredModelAliasMapOutput {
	return o
}

func (o RegisteredModelAliasMapOutput) MapIndex(k pulumi.StringInput) RegisteredModelAliasOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RegisteredModelAlias {
		return vs[0].(map[string]*RegisteredModelAlias)[vs[1].(string)]
	}).(RegisteredModelAliasOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelAliasInput)(nil)).Elem(), &RegisteredModelAlias{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelAliasArrayInput)(nil)).Elem(), RegisteredModelAliasArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelAliasMapInput)(nil)).Elem(), RegisteredModelAliasMap{})
	pulumi.RegisterOutputType(RegisteredModelAliasOutput{})
	pulumi.RegisterOutputType(RegisteredModelAliasArrayOutput{})
	pulumi.RegisterOutputType(RegisteredModelAliasMapOutput{})
}
