// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Searches model versions with an optional MLflow filter string.
//
// REST: `/api/2.0/mlflow/model-versions/search`.
//
// ## Example Usage
func SearchModelVersions(ctx *pulumi.Context, args *SearchModelVersionsArgs, opts ...pulumi.InvokeOption) (*SearchModelVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv SearchModelVersionsResult
	err := ctx.Invoke("mlflow:registry:searchModelVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type SearchModelVersionsArgs struct {
	Filter     *string `pulumi:"filter"`
	MaxResults *int    `pulumi:"maxResults"`
}

type SearchModelVersionsResult struct {
	ModelVersions []ModelVersionResult `pulumi:"modelVersions"`
}

func SearchModelVersionsOutput(ctx *pulumi.Context, args SearchModelVersionsOutputArgs, opts ...pulumi.InvokeOption) SearchModelVersionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (SearchModelVersionsResultOutput, error) {
			args := v.(SearchModelVersionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:searchModelVersions", args, SearchModelVersionsResultOutput{}, options).(SearchModelVersionsResultOutput), nil
		}).(SearchModelVersionsResultOutput)
}

type SearchModelVersionsOutputArgs struct {
	Filter     pulumi.StringPtrInput `pulumi:"filter"`
	MaxResults pulumi.IntPtrInput    `pulumi:"maxResults"`
}

func (SearchModelVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchModelVersionsArgs)(nil)).Elem()
}

type SearchModelVersionsResultOutput struct{ *pulumi.OutputState }

func (SearchModelVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchModelVersionsResult)(nil)).Elem()
}

func (o SearchModelVersionsResultOutput) ToSearchModelVersionsResultOutput() SearchModelVersionsResultOutput {
	return o
}

func (o SearchModelVersionsResultOutput) ToSearchModelVersionsResultOutputWithContext(ctx context.Context) SearchModelVersionsResultOutput {
	return o
}

func (o SearchModelVersionsResultOutput) ModelVersions() ModelVersionResultArrayOutput {
	return o.ApplyT(func(v SearchModelVersionsResult) []ModelVersionResult { return v.ModelVersions }).(ModelVersionResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(SearchModelVersionsResultOutput{})
}
