// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Searches registered models with an optional MLflow [filter string](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-registeredmodels).
//
// REST: `/api/2.0/mlflow/registered-models/search`.
//
// ## Example Usage
func SearchRegisteredModels(ctx *pulumi.Context, args *SearchRegisteredModelsArgs, opts ...pulumi.InvokeOption) (*SearchRegisteredModelsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv SearchRegisteredModelsResult
	err := ctx.Invoke("mlflow:registry:searchRegisteredModels", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type SearchRegisteredModelsArgs struct {
	Filter     *string `pulumi:"filter"`
	MaxResults *int    `pulumi:"maxResults"`
}

type SearchRegisteredModelsResult struct {
	RegisteredModels []RegisteredModelResult `pulumi:"registeredModels"`
}

func SearchRegisteredModelsOutput(ctx *pulumi.Context, args SearchRegisteredModelsOutputArgs, opts ...pulumi.InvokeOption) SearchRegisteredModelsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (SearchRegisteredModelsResultOutput, error) {
			args := v.(SearchRegisteredModelsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:registry:searchRegisteredModels", args, SearchRegisteredModelsResultOutput{}, options).(SearchRegisteredModelsResultOutput), nil
		}).(SearchRegisteredModelsResultOutput)
}

type SearchRegisteredModelsOutputArgs struct {
	Filter     pulumi.StringPtrInput `pulumi:"filter"`
	MaxResults pulumi.IntPtrInput    `pulumi:"maxResults"`
}

func (SearchRegisteredModelsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchRegisteredModelsArgs)(nil)).Elem()
}

type SearchRegisteredModelsResultOutput struct{ *pulumi.OutputState }

func (SearchRegisteredModelsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchRegisteredModelsResult)(nil)).Elem()
}

func (o SearchRegisteredModelsResultOutput) ToSearchRegisteredModelsResultOutput() SearchRegisteredModelsResultOutput {
	return o
}

func (o SearchRegisteredModelsResultOutput) ToSearchRegisteredModelsResultOutputWithContext(ctx context.Context) SearchRegisteredModelsResultOutput {
	return o
}

func (o SearchRegisteredModelsResultOutput) RegisteredModels() RegisteredModelResultArrayOutput {
	return o.ApplyT(func(v SearchRegisteredModelsResult) []RegisteredModelResult { return v.RegisteredModels }).(RegisteredModelResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(SearchRegisteredModelsResultOutput{})
}
