// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Returns the latest version of a registered model per stage (or overall).
 *
 * REST: `/api/2.0/mlflow/registered-models/get-latest-versions`.
 *
 * ## Example Usage
 */
export function getLatestVersions(args: GetLatestVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetLatestVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:getLatestVersions", {
        "name": args.name,
        "stages": args.stages,
    }, opts);
}

export interface GetLatestVersionsArgs {
    name: string;
    stages?: string[];
}

export interface GetLatestVersionsResult {
    readonly modelVersions: outputs.registry.ModelVersionResult[];
}
/**
 * Returns the latest version of a registered model per stage (or overall).
 *
 * REST: `/api/2.0/mlflow/registered-models/get-latest-versions`.
 *
 * ## Example Usage
 */
export function getLatestVersionsOutput(args: GetLatestVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLatestVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:getLatestVersions", {
        "name": args.name,
        "stages": args.stages,
    }, opts);
}

export interface GetLatestVersionsOutputArgs {
    name: pulumi.Input<string>;
    stages?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
