// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Resolves an alias on a registered model to the model version it currently points at — useful for reading which version is, for example, `champion`.
 *
 * REST: `/api/2.0/mlflow/registered-models/alias` (get).
 *
 * ## Example Usage
 */
export function getModelVersionByAlias(args: GetModelVersionByAliasArgs, opts?: pulumi.InvokeOptions): Promise<GetModelVersionByAliasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:getModelVersionByAlias", {
        "alias": args.alias,
        "name": args.name,
    }, opts);
}

export interface GetModelVersionByAliasArgs {
    alias: string;
    name: string;
}

export interface GetModelVersionByAliasResult {
    readonly aliases: string[];
    readonly currentStage: string;
    readonly description: string;
    readonly name: string;
    readonly runId: string;
    readonly source: string;
    readonly status: string;
    readonly tags: {[key: string]: string};
    readonly version: string;
}
/**
 * Resolves an alias on a registered model to the model version it currently points at — useful for reading which version is, for example, `champion`.
 *
 * REST: `/api/2.0/mlflow/registered-models/alias` (get).
 *
 * ## Example Usage
 */
export function getModelVersionByAliasOutput(args: GetModelVersionByAliasOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetModelVersionByAliasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:getModelVersionByAlias", {
        "alias": args.alias,
        "name": args.name,
    }, opts);
}

export interface GetModelVersionByAliasOutputArgs {
    alias: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
