// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Returns the artifact download URI for a model version.
 *
 * REST: `/api/2.0/mlflow/model-versions/get-download-uri`.
 *
 * ## Example Usage
 */
export function getModelVersionDownloadUri(args: GetModelVersionDownloadUriArgs, opts?: pulumi.InvokeOptions): Promise<GetModelVersionDownloadUriResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:getModelVersionDownloadUri", {
        "name": args.name,
        "version": args.version,
    }, opts);
}

export interface GetModelVersionDownloadUriArgs {
    name: string;
    version: string;
}

export interface GetModelVersionDownloadUriResult {
    readonly artifactUri: string;
}
/**
 * Returns the artifact download URI for a model version.
 *
 * REST: `/api/2.0/mlflow/model-versions/get-download-uri`.
 *
 * ## Example Usage
 */
export function getModelVersionDownloadUriOutput(args: GetModelVersionDownloadUriOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetModelVersionDownloadUriResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:getModelVersionDownloadUri", {
        "name": args.name,
        "version": args.version,
    }, opts);
}

export interface GetModelVersionDownloadUriOutputArgs {
    name: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
