// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Looks up a specific model version by model name and version number.
 *
 * REST: `/api/2.0/mlflow/model-versions/get`.
 *
 * ## Example Usage
 */
export function getModelVersion(args: GetModelVersionArgs, opts?: pulumi.InvokeOptions): Promise<GetModelVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:getModelVersion", {
        "name": args.name,
        "version": args.version,
    }, opts);
}

export interface GetModelVersionArgs {
    name: string;
    version: string;
}

export interface GetModelVersionResult {
    readonly aliases: string[];
    readonly currentStage: string;
    readonly description: string;
    readonly name: string;
    readonly runId: string;
    readonly source: string;
    readonly status: string;
    readonly tags: {[key: string]: string};
    readonly version: string;
}
/**
 * Looks up a specific model version by model name and version number.
 *
 * REST: `/api/2.0/mlflow/model-versions/get`.
 *
 * ## Example Usage
 */
export function getModelVersionOutput(args: GetModelVersionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetModelVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:getModelVersion", {
        "name": args.name,
        "version": args.version,
    }, opts);
}

export interface GetModelVersionOutputArgs {
    name: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
