// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Looks up a registered model in the [Model Registry](https://mlflow.org/docs/latest/ml/model-registry/) by name.
 *
 * REST: `/api/2.0/mlflow/registered-models/get`.
 *
 * ## Example Usage
 */
export function getRegisteredModel(args: GetRegisteredModelArgs, opts?: pulumi.InvokeOptions): Promise<GetRegisteredModelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:getRegisteredModel", {
        "name": args.name,
    }, opts);
}

export interface GetRegisteredModelArgs {
    name: string;
}

export interface GetRegisteredModelResult {
    readonly creationTimestamp: number;
    readonly description: string;
    readonly lastUpdatedTimestamp: number;
    readonly name: string;
    readonly tags: {[key: string]: string};
}
/**
 * Looks up a registered model in the [Model Registry](https://mlflow.org/docs/latest/ml/model-registry/) by name.
 *
 * REST: `/api/2.0/mlflow/registered-models/get`.
 *
 * ## Example Usage
 */
export function getRegisteredModelOutput(args: GetRegisteredModelOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRegisteredModelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:getRegisteredModel", {
        "name": args.name,
    }, opts);
}

export interface GetRegisteredModelOutputArgs {
    name: pulumi.Input<string>;
}
