// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetLatestVersionsArgs, GetLatestVersionsResult, GetLatestVersionsOutputArgs } from "./getLatestVersions";
export const getLatestVersions: typeof import("./getLatestVersions").getLatestVersions = null as any;
export const getLatestVersionsOutput: typeof import("./getLatestVersions").getLatestVersionsOutput = null as any;
utilities.lazyLoad(exports, ["getLatestVersions","getLatestVersionsOutput"], () => require("./getLatestVersions"));

export { GetModelVersionArgs, GetModelVersionResult, GetModelVersionOutputArgs } from "./getModelVersion";
export const getModelVersion: typeof import("./getModelVersion").getModelVersion = null as any;
export const getModelVersionOutput: typeof import("./getModelVersion").getModelVersionOutput = null as any;
utilities.lazyLoad(exports, ["getModelVersion","getModelVersionOutput"], () => require("./getModelVersion"));

export { GetModelVersionByAliasArgs, GetModelVersionByAliasResult, GetModelVersionByAliasOutputArgs } from "./getModelVersionByAlias";
export const getModelVersionByAlias: typeof import("./getModelVersionByAlias").getModelVersionByAlias = null as any;
export const getModelVersionByAliasOutput: typeof import("./getModelVersionByAlias").getModelVersionByAliasOutput = null as any;
utilities.lazyLoad(exports, ["getModelVersionByAlias","getModelVersionByAliasOutput"], () => require("./getModelVersionByAlias"));

export { GetModelVersionDownloadUriArgs, GetModelVersionDownloadUriResult, GetModelVersionDownloadUriOutputArgs } from "./getModelVersionDownloadUri";
export const getModelVersionDownloadUri: typeof import("./getModelVersionDownloadUri").getModelVersionDownloadUri = null as any;
export const getModelVersionDownloadUriOutput: typeof import("./getModelVersionDownloadUri").getModelVersionDownloadUriOutput = null as any;
utilities.lazyLoad(exports, ["getModelVersionDownloadUri","getModelVersionDownloadUriOutput"], () => require("./getModelVersionDownloadUri"));

export { GetRegisteredModelArgs, GetRegisteredModelResult, GetRegisteredModelOutputArgs } from "./getRegisteredModel";
export const getRegisteredModel: typeof import("./getRegisteredModel").getRegisteredModel = null as any;
export const getRegisteredModelOutput: typeof import("./getRegisteredModel").getRegisteredModelOutput = null as any;
utilities.lazyLoad(exports, ["getRegisteredModel","getRegisteredModelOutput"], () => require("./getRegisteredModel"));

export { ModelVersionArgs } from "./modelVersion";
export type ModelVersion = import("./modelVersion").ModelVersion;
export const ModelVersion: typeof import("./modelVersion").ModelVersion = null as any;
utilities.lazyLoad(exports, ["ModelVersion"], () => require("./modelVersion"));

export { RegisteredModelArgs } from "./registeredModel";
export type RegisteredModel = import("./registeredModel").RegisteredModel;
export const RegisteredModel: typeof import("./registeredModel").RegisteredModel = null as any;
utilities.lazyLoad(exports, ["RegisteredModel"], () => require("./registeredModel"));

export { RegisteredModelAliasArgs } from "./registeredModelAlias";
export type RegisteredModelAlias = import("./registeredModelAlias").RegisteredModelAlias;
export const RegisteredModelAlias: typeof import("./registeredModelAlias").RegisteredModelAlias = null as any;
utilities.lazyLoad(exports, ["RegisteredModelAlias"], () => require("./registeredModelAlias"));

export { RegisteredModelTagArgs } from "./registeredModelTag";
export type RegisteredModelTag = import("./registeredModelTag").RegisteredModelTag;
export const RegisteredModelTag: typeof import("./registeredModelTag").RegisteredModelTag = null as any;
utilities.lazyLoad(exports, ["RegisteredModelTag"], () => require("./registeredModelTag"));

export { SearchModelVersionsArgs, SearchModelVersionsResult, SearchModelVersionsOutputArgs } from "./searchModelVersions";
export const searchModelVersions: typeof import("./searchModelVersions").searchModelVersions = null as any;
export const searchModelVersionsOutput: typeof import("./searchModelVersions").searchModelVersionsOutput = null as any;
utilities.lazyLoad(exports, ["searchModelVersions","searchModelVersionsOutput"], () => require("./searchModelVersions"));

export { SearchRegisteredModelsArgs, SearchRegisteredModelsResult, SearchRegisteredModelsOutputArgs } from "./searchRegisteredModels";
export const searchRegisteredModels: typeof import("./searchRegisteredModels").searchRegisteredModels = null as any;
export const searchRegisteredModelsOutput: typeof import("./searchRegisteredModels").searchRegisteredModelsOutput = null as any;
utilities.lazyLoad(exports, ["searchRegisteredModels","searchRegisteredModelsOutput"], () => require("./searchRegisteredModels"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mlflow:registry:ModelVersion":
                return new ModelVersion(name, <any>undefined, { urn })
            case "mlflow:registry:RegisteredModel":
                return new RegisteredModel(name, <any>undefined, { urn })
            case "mlflow:registry:RegisteredModelAlias":
                return new RegisteredModelAlias(name, <any>undefined, { urn })
            case "mlflow:registry:RegisteredModelTag":
                return new RegisteredModelTag(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mlflow", "registry", _module)
