// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a version of a [registered model](https://mlflow.org/docs/latest/ml/model-registry/) — an immutable snapshot of a model's artifacts.
 *
 * The `source`, `runId` and `runLink` are set once: changing any of them replaces the version. Only `description` and `tags` update in place. On create, the provider waits until the version's status is `READY`.
 *
 * > **Note:** `stage` (None/Staging/Production/Archived) is **deprecated in MLflow 3**. Prefer [`RegisteredModelAlias`](/registry/registeredmodelalias) to drive deployments. Setting `stage` against a 3.x server emits a warning.
 *
 * REST endpoints: `/api/2.0/mlflow/model-versions/{create,get,update,delete,set-tag,delete-tag,transition-stage}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-modelversion).
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Model versions can be imported using `<model-name>/<version>`:
 *
 * ```sh
 * pulumi import mlflow:registry:ModelVersion fraud-v1 fraud-detector/1
 * ```
 */
export class ModelVersion extends pulumi.CustomResource {
    /**
     * Get an existing ModelVersion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ModelVersion {
        return new ModelVersion(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mlflow:registry:ModelVersion';

    /**
     * Returns true if the given object is an instance of ModelVersion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ModelVersion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ModelVersion.__pulumiType;
    }

    /**
     * Aliases currently pointing at this version.
     */
    declare public /*out*/ readonly aliases: pulumi.Output<string[] | undefined>;
    /**
     * Creation time, in epoch milliseconds.
     */
    declare public /*out*/ readonly creationTimestamp: pulumi.Output<number>;
    /**
     * The version's current stage (deprecated in MLflow 3; prefer aliases).
     */
    declare public /*out*/ readonly currentStage: pulumi.Output<string>;
    /**
     * Optional human-readable description. Updated in place.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Last update time, in epoch milliseconds.
     */
    declare public /*out*/ readonly lastUpdatedTimestamp: pulumi.Output<number>;
    /**
     * Parent registered model name. Changing it replaces the version.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Optional MLflow run that produced the model. Changing it replaces the version.
     */
    declare public readonly runId: pulumi.Output<string | undefined>;
    /**
     * Optional link to the source run. Changing it replaces the version.
     */
    declare public readonly runLink: pulumi.Output<string | undefined>;
    /**
     * URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
     */
    declare public readonly source: pulumi.Output<string>;
    /**
     * Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
     *
     * @deprecated Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
     */
    declare public readonly stage: pulumi.Output<string | undefined>;
    /**
     * Registration status; the provider waits for READY on create.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Optional key/value metadata tags. Synced in place.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Server-assigned version number (immutable).
     */
    declare public /*out*/ readonly version: pulumi.Output<string>;

    /**
     * Create a ModelVersion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ModelVersionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["runId"] = args?.runId;
            resourceInputs["runLink"] = args?.runLink;
            resourceInputs["source"] = args?.source;
            resourceInputs["stage"] = args?.stage;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["aliases"] = undefined /*out*/;
            resourceInputs["creationTimestamp"] = undefined /*out*/;
            resourceInputs["currentStage"] = undefined /*out*/;
            resourceInputs["lastUpdatedTimestamp"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        } else {
            resourceInputs["aliases"] = undefined /*out*/;
            resourceInputs["creationTimestamp"] = undefined /*out*/;
            resourceInputs["currentStage"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["lastUpdatedTimestamp"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["runId"] = undefined /*out*/;
            resourceInputs["runLink"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["stage"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["name", "runId", "runLink", "source"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ModelVersion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ModelVersion resource.
 */
export interface ModelVersionArgs {
    /**
     * Optional human-readable description. Updated in place.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Parent registered model name. Changing it replaces the version.
     */
    name: pulumi.Input<string>;
    /**
     * Optional MLflow run that produced the model. Changing it replaces the version.
     */
    runId?: pulumi.Input<string | undefined>;
    /**
     * Optional link to the source run. Changing it replaces the version.
     */
    runLink?: pulumi.Input<string | undefined>;
    /**
     * URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
     */
    source: pulumi.Input<string>;
    /**
     * Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
     *
     * @deprecated Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.
     */
    stage?: pulumi.Input<string | undefined>;
    /**
     * Optional key/value metadata tags. Synced in place.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
