// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a model in the [MLflow Model Registry](https://mlflow.org/docs/latest/ml/model-registry/) — a named container that groups the versions of a model.
 *
 * The model `name` is the resource identity; changing it replaces the resource. Only `description` and `tags` are updated in place.
 *
 * REST endpoints: `/api/2.0/mlflow/registered-models/{create,get,update,delete,set-tag,delete-tag}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-registeredmodel).
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Registered models can be imported using the model name:
 *
 * ```sh
 * pulumi import mlflow:registry:RegisteredModel fraud fraud-detector
 * ```
 */
export class RegisteredModel extends pulumi.CustomResource {
    /**
     * Get an existing RegisteredModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RegisteredModel {
        return new RegisteredModel(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mlflow:registry:RegisteredModel';

    /**
     * Returns true if the given object is an instance of RegisteredModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RegisteredModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RegisteredModel.__pulumiType;
    }

    /**
     * Model creation time, in epoch milliseconds.
     */
    declare public /*out*/ readonly creationTimestamp: pulumi.Output<number>;
    /**
     * Optional human-readable description. Updated in place.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Last update time, in epoch milliseconds.
     */
    declare public /*out*/ readonly lastUpdatedTimestamp: pulumi.Output<number>;
    /**
     * Unique name of the registered model. This is the resource identity; changing it replaces the resource.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a RegisteredModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RegisteredModelArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["creationTimestamp"] = undefined /*out*/;
            resourceInputs["lastUpdatedTimestamp"] = undefined /*out*/;
        } else {
            resourceInputs["creationTimestamp"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["lastUpdatedTimestamp"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["name"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(RegisteredModel.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RegisteredModel resource.
 */
export interface RegisteredModelArgs {
    /**
     * Optional human-readable description. Updated in place.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Unique name of the registered model. This is the resource identity; changing it replaces the resource.
     */
    name: pulumi.Input<string>;
    /**
     * Optional key/value metadata tags. Synced in place via set-tag/delete-tag.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
