// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a named [alias](https://mlflow.org/docs/latest/ml/model-registry/#deploy-and-organize-models-with-aliases-and-tags) on a registered model that points at a specific version (for example `champion` → version 3).
 *
 * Aliases are mutable pointers and are the **recommended** way to drive deployments; they supersede the deprecated model *stages*. `version` is updatable — changing it re-points the alias to a different version — while `modelName` and `alias` changes replace the resource.
 *
 * REST endpoints: `/api/2.0/mlflow/registered-models/alias` (set/delete/get) — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#set-registered-model-alias).
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Aliases can be imported using `<model-name>/<alias>`:
 *
 * ```sh
 * pulumi import mlflow:registry:RegisteredModelAlias champion fraud-detector/champion
 * ```
 */
export class RegisteredModelAlias extends pulumi.CustomResource {
    /**
     * Get an existing RegisteredModelAlias resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RegisteredModelAlias {
        return new RegisteredModelAlias(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mlflow:registry:RegisteredModelAlias';

    /**
     * Returns true if the given object is an instance of RegisteredModelAlias.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RegisteredModelAlias {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RegisteredModelAlias.__pulumiType;
    }

    /**
     * Alias name, e.g. "champion". Changing it replaces the resource.
     */
    declare public readonly alias: pulumi.Output<string>;
    /**
     * Registered model the alias belongs to. Changing it replaces the resource.
     */
    declare public readonly modelName: pulumi.Output<string>;
    /**
     * Model version the alias points at. Updating it re-points the alias in place.
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a RegisteredModelAlias resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RegisteredModelAliasArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.alias === undefined && !opts.urn) {
                throw new Error("Missing required property 'alias'");
            }
            if (args?.modelName === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelName'");
            }
            if (args?.version === undefined && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["alias"] = args?.alias;
            resourceInputs["modelName"] = args?.modelName;
            resourceInputs["version"] = args?.version;
        } else {
            resourceInputs["alias"] = undefined /*out*/;
            resourceInputs["modelName"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["alias", "modelName"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(RegisteredModelAlias.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RegisteredModelAlias resource.
 */
export interface RegisteredModelAliasArgs {
    /**
     * Alias name, e.g. "champion". Changing it replaces the resource.
     */
    alias: pulumi.Input<string>;
    /**
     * Registered model the alias belongs to. Changing it replaces the resource.
     */
    modelName: pulumi.Input<string>;
    /**
     * Model version the alias points at. Updating it re-points the alias in place.
     */
    version: pulumi.Input<string>;
}
