// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a single key/value tag on a registered model that is owned elsewhere (e.g. created by a training pipeline). Unlike the `tags` map on RegisteredModel it does not own the model: it sets the tag on create, updates the value in place, and removes only that tag on delete. This mirrors the `aws.ec2.Tag`-style pattern for managing one attribute of an externally-owned resource. Backed by the MLflow `registered-models/set-tag` and `registered-models/delete-tag` endpoints.
 *
 * ## Example Usage
 *
 * ## Import
 *
 * ```sh
 * pulumi import mlflow:registry:RegisteredModelTag serving-host <modelName>/<key>
 * ```
 */
export class RegisteredModelTag extends pulumi.CustomResource {
    /**
     * Get an existing RegisteredModelTag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RegisteredModelTag {
        return new RegisteredModelTag(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mlflow:registry:RegisteredModelTag';

    /**
     * Returns true if the given object is an instance of RegisteredModelTag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RegisteredModelTag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RegisteredModelTag.__pulumiType;
    }

    declare public readonly key: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a RegisteredModelTag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RegisteredModelTagArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["key"] = args?.key;
            resourceInputs["name"] = args?.name;
            resourceInputs["value"] = args?.value;
        } else {
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["key", "name"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(RegisteredModelTag.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RegisteredModelTag resource.
 */
export interface RegisteredModelTagArgs {
    key: pulumi.Input<string>;
    name: pulumi.Input<string>;
    value: pulumi.Input<string>;
}
