// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Searches model versions with an optional MLflow filter string.
 *
 * REST: `/api/2.0/mlflow/model-versions/search`.
 *
 * ## Example Usage
 */
export function searchModelVersions(args?: SearchModelVersionsArgs, opts?: pulumi.InvokeOptions): Promise<SearchModelVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:searchModelVersions", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchModelVersionsArgs {
    filter?: string;
    maxResults?: number;
}

export interface SearchModelVersionsResult {
    readonly modelVersions: outputs.registry.ModelVersionResult[];
}
/**
 * Searches model versions with an optional MLflow filter string.
 *
 * REST: `/api/2.0/mlflow/model-versions/search`.
 *
 * ## Example Usage
 */
export function searchModelVersionsOutput(args?: SearchModelVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SearchModelVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:searchModelVersions", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchModelVersionsOutputArgs {
    filter?: pulumi.Input<string | undefined>;
    maxResults?: pulumi.Input<number | undefined>;
}
