// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Searches registered models with an optional MLflow [filter string](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-registeredmodels).
 *
 * REST: `/api/2.0/mlflow/registered-models/search`.
 *
 * ## Example Usage
 */
export function searchRegisteredModels(args?: SearchRegisteredModelsArgs, opts?: pulumi.InvokeOptions): Promise<SearchRegisteredModelsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:registry:searchRegisteredModels", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchRegisteredModelsArgs {
    filter?: string;
    maxResults?: number;
}

export interface SearchRegisteredModelsResult {
    readonly registeredModels: outputs.registry.RegisteredModelResult[];
}
/**
 * Searches registered models with an optional MLflow [filter string](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-registeredmodels).
 *
 * REST: `/api/2.0/mlflow/registered-models/search`.
 *
 * ## Example Usage
 */
export function searchRegisteredModelsOutput(args?: SearchRegisteredModelsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SearchRegisteredModelsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:registry:searchRegisteredModels", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchRegisteredModelsOutputArgs {
    filter?: pulumi.Input<string | undefined>;
    maxResults?: pulumi.Input<number | undefined>;
}
