# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 insecure_skip_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 token: pulumi.Input[Optional[_builtins.str]] = None,
                 tracking_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.bool] insecure_skip_verify: Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
        :param pulumi.Input[_builtins.str] password: Password for HTTP Basic authentication.
        :param pulumi.Input[_builtins.str] token: Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
        :param pulumi.Input[_builtins.str] tracking_uri: URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
        :param pulumi.Input[_builtins.str] username: Username for HTTP Basic authentication against the MLflow tracking server.
        """
        if insecure_skip_verify is not None:
            pulumi.set(__self__, "insecure_skip_verify", insecure_skip_verify)
        if password is None:
            password = (_utilities.get_env('MLFLOW_TRACKING_PASSWORD') or '')
        if password is not None:
            pulumi.set(__self__, "password", password)
        if token is None:
            token = (_utilities.get_env('MLFLOW_TRACKING_TOKEN') or '')
        if token is not None:
            pulumi.set(__self__, "token", token)
        if tracking_uri is None:
            tracking_uri = (_utilities.get_env('MLFLOW_TRACKING_URI') or '')
        if tracking_uri is not None:
            pulumi.set(__self__, "tracking_uri", tracking_uri)
        if username is None:
            username = (_utilities.get_env('MLFLOW_TRACKING_USERNAME') or '')
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter(name="insecureSkipVerify")
    def insecure_skip_verify(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
        """
        return pulumi.get(self, "insecure_skip_verify")

    @insecure_skip_verify.setter
    def insecure_skip_verify(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "insecure_skip_verify", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Password for HTTP Basic authentication.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token", value)

    @_builtins.property
    @pulumi.getter(name="trackingUri")
    def tracking_uri(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
        """
        return pulumi.get(self, "tracking_uri")

    @tracking_uri.setter
    def tracking_uri(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "tracking_uri", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Username for HTTP Basic authentication against the MLflow tracking server.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("pulumi:providers:mlflow")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 insecure_skip_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 token: pulumi.Input[Optional[_builtins.str]] = None,
                 tracking_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Mlflow resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] insecure_skip_verify: Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
        :param pulumi.Input[_builtins.str] password: Password for HTTP Basic authentication.
        :param pulumi.Input[_builtins.str] token: Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
        :param pulumi.Input[_builtins.str] tracking_uri: URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
        :param pulumi.Input[_builtins.str] username: Username for HTTP Basic authentication against the MLflow tracking server.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Mlflow resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 insecure_skip_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 token: pulumi.Input[Optional[_builtins.str]] = None,
                 tracking_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["insecure_skip_verify"] = pulumi.Output.from_input(insecure_skip_verify).apply(pulumi.runtime.to_json) if insecure_skip_verify is not None else None
            if password is None:
                password = (_utilities.get_env('MLFLOW_TRACKING_PASSWORD') or '')
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            if token is None:
                token = (_utilities.get_env('MLFLOW_TRACKING_TOKEN') or '')
            __props__.__dict__["token"] = None if token is None else pulumi.Output.secret(token)
            if tracking_uri is None:
                tracking_uri = (_utilities.get_env('MLFLOW_TRACKING_URI') or '')
            __props__.__dict__["tracking_uri"] = tracking_uri
            if username is None:
                username = (_utilities.get_env('MLFLOW_TRACKING_USERNAME') or '')
            __props__.__dict__["username"] = username
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'mlflow',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Password for HTTP Basic authentication.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
        """
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter(name="trackingUri")
    def tracking_uri(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
        """
        return pulumi.get(self, "tracking_uri")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Username for HTTP Basic authentication against the MLflow tracking server.
        """
        return pulumi.get(self, "username")

