# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetRegisteredModelPermissionResult',
    'AwaitableGetRegisteredModelPermissionResult',
    'get_registered_model_permission',
    'get_registered_model_permission_output',
]

@pulumi.output_type
class GetRegisteredModelPermissionResult:
    def __init__(__self__, permission=None):
        if permission and not isinstance(permission, str):
            raise TypeError("Expected argument 'permission' to be a str")
        pulumi.set(__self__, "permission", permission)

    @_builtins.property
    @pulumi.getter
    def permission(self) -> _builtins.str:
        return pulumi.get(self, "permission")


class AwaitableGetRegisteredModelPermissionResult(GetRegisteredModelPermissionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRegisteredModelPermissionResult(
            permission=self.permission)


def get_registered_model_permission(name: Optional[_builtins.str] = None,
                                    username: Optional[_builtins.str] = None,
                                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRegisteredModelPermissionResult:
    """
    Returns the permission level a user has on an MLflow registered model.

    > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['username'] = username
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:auth:getRegisteredModelPermission', __args__, opts=opts, typ=GetRegisteredModelPermissionResult).value

    return AwaitableGetRegisteredModelPermissionResult(
        permission=pulumi.get(__ret__, 'permission'))
def get_registered_model_permission_output(name: pulumi.Input[Optional[_builtins.str]] = None,
                                           username: pulumi.Input[Optional[_builtins.str]] = None,
                                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRegisteredModelPermissionResult]:
    """
    Returns the permission level a user has on an MLflow registered model.

    > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['username'] = username
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:auth:getRegisteredModelPermission', __args__, opts=opts, typ=GetRegisteredModelPermissionResult)
    return __ret__.apply(lambda __response__: GetRegisteredModelPermissionResult(
        permission=pulumi.get(__response__, 'permission')))
