# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['RegisteredModelPermissionArgs', 'RegisteredModelPermission']

@pulumi.input_type
class RegisteredModelPermissionArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 permission: pulumi.Input[_builtins.str],
                 username: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a RegisteredModelPermission resource.

        :param pulumi.Input[_builtins.str] name: The registered model name. Changing this forces replacement.
        :param pulumi.Input[_builtins.str] permission: The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
        :param pulumi.Input[_builtins.str] username: The user to grant the permission to. Changing this forces replacement.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "permission", permission)
        pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The registered model name. Changing this forces replacement.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def permission(self) -> pulumi.Input[_builtins.str]:
        """
        The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
        """
        return pulumi.get(self, "permission")

    @permission.setter
    def permission(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "permission", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[_builtins.str]:
        """
        The user to grant the permission to. Changing this forces replacement.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "username", value)


@pulumi.type_token("mlflow:auth:RegisteredModelPermission")
class RegisteredModelPermission(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 permission: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Grants a user a permission level on an MLflow registered model. Valid `permission` values are `READ`, `EDIT`, `MANAGE` and `NO_PERMISSIONS`; only `permission` can be updated in place (changing the model or user replaces the grant).

        > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).

        ## Example Usage

        ## Import

        Import an existing resource with its id:

        ```sh
        $ pulumi import mlflow:auth:RegisteredModelPermission example <name>/<username>
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The registered model name. Changing this forces replacement.
        :param pulumi.Input[_builtins.str] permission: The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
        :param pulumi.Input[_builtins.str] username: The user to grant the permission to. Changing this forces replacement.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RegisteredModelPermissionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Grants a user a permission level on an MLflow registered model. Valid `permission` values are `READ`, `EDIT`, `MANAGE` and `NO_PERMISSIONS`; only `permission` can be updated in place (changing the model or user replaces the grant).

        > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).

        ## Example Usage

        ## Import

        Import an existing resource with its id:

        ```sh
        $ pulumi import mlflow:auth:RegisteredModelPermission example <name>/<username>
        ```


        :param str resource_name: The name of the resource.
        :param RegisteredModelPermissionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RegisteredModelPermissionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 permission: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RegisteredModelPermissionArgs.__new__(RegisteredModelPermissionArgs)

            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if permission is None and not opts.urn:
                raise TypeError("Missing required property 'permission'")
            __props__.__dict__["permission"] = permission
            if username is None and not opts.urn:
                raise TypeError("Missing required property 'username'")
            __props__.__dict__["username"] = username
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["name", "username"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(RegisteredModelPermission, __self__).__init__(
            'mlflow:auth:RegisteredModelPermission',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'RegisteredModelPermission':
        """
        Get an existing RegisteredModelPermission resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = RegisteredModelPermissionArgs.__new__(RegisteredModelPermissionArgs)

        __props__.__dict__["name"] = None
        __props__.__dict__["permission"] = None
        __props__.__dict__["username"] = None
        return RegisteredModelPermission(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The registered model name. Changing this forces replacement.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def permission(self) -> pulumi.Output[_builtins.str]:
        """
        The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
        """
        return pulumi.get(self, "permission")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        """
        The user to grant the permission to. Changing this forces replacement.
        """
        return pulumi.get(self, "username")

