// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mlflow

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up an existing MLflow experiment by its server-assigned ID. Wraps [`experiments/get`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment).
//
// ## Example Usage
func LookupExperiment(ctx *pulumi.Context, args *LookupExperimentArgs, opts ...pulumi.InvokeOption) (*LookupExperimentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupExperimentResult
	err := ctx.Invoke("mlflow:index:getExperiment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupExperimentArgs struct {
	ExperimentId string `pulumi:"experimentId"`
}

type LookupExperimentResult struct {
	ArtifactLocation string            `pulumi:"artifactLocation"`
	ExperimentId     string            `pulumi:"experimentId"`
	LifecycleStage   string            `pulumi:"lifecycleStage"`
	Name             string            `pulumi:"name"`
	Tags             map[string]string `pulumi:"tags"`
}

func LookupExperimentOutput(ctx *pulumi.Context, args LookupExperimentOutputArgs, opts ...pulumi.InvokeOption) LookupExperimentResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupExperimentResultOutput, error) {
			args := v.(LookupExperimentArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:index:getExperiment", args, LookupExperimentResultOutput{}, options).(LookupExperimentResultOutput), nil
		}).(LookupExperimentResultOutput)
}

type LookupExperimentOutputArgs struct {
	ExperimentId pulumi.StringInput `pulumi:"experimentId"`
}

func (LookupExperimentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExperimentArgs)(nil)).Elem()
}

type LookupExperimentResultOutput struct{ *pulumi.OutputState }

func (LookupExperimentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExperimentResult)(nil)).Elem()
}

func (o LookupExperimentResultOutput) ToLookupExperimentResultOutput() LookupExperimentResultOutput {
	return o
}

func (o LookupExperimentResultOutput) ToLookupExperimentResultOutputWithContext(ctx context.Context) LookupExperimentResultOutput {
	return o
}

func (o LookupExperimentResultOutput) ArtifactLocation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExperimentResult) string { return v.ArtifactLocation }).(pulumi.StringOutput)
}

func (o LookupExperimentResultOutput) ExperimentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExperimentResult) string { return v.ExperimentId }).(pulumi.StringOutput)
}

func (o LookupExperimentResultOutput) LifecycleStage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExperimentResult) string { return v.LifecycleStage }).(pulumi.StringOutput)
}

func (o LookupExperimentResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExperimentResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupExperimentResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupExperimentResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupExperimentResultOutput{})
}
