// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mlflow

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up an existing MLflow experiment by its unique name. Wraps [`experiments/get-by-name`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment-by-name).
//
// ## Example Usage
func GetExperimentByName(ctx *pulumi.Context, args *GetExperimentByNameArgs, opts ...pulumi.InvokeOption) (*GetExperimentByNameResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetExperimentByNameResult
	err := ctx.Invoke("mlflow:index:getExperimentByName", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetExperimentByNameArgs struct {
	Name string `pulumi:"name"`
}

type GetExperimentByNameResult struct {
	ArtifactLocation string            `pulumi:"artifactLocation"`
	ExperimentId     string            `pulumi:"experimentId"`
	LifecycleStage   string            `pulumi:"lifecycleStage"`
	Name             string            `pulumi:"name"`
	Tags             map[string]string `pulumi:"tags"`
}

func GetExperimentByNameOutput(ctx *pulumi.Context, args GetExperimentByNameOutputArgs, opts ...pulumi.InvokeOption) GetExperimentByNameResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetExperimentByNameResultOutput, error) {
			args := v.(GetExperimentByNameArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:index:getExperimentByName", args, GetExperimentByNameResultOutput{}, options).(GetExperimentByNameResultOutput), nil
		}).(GetExperimentByNameResultOutput)
}

type GetExperimentByNameOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetExperimentByNameOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetExperimentByNameArgs)(nil)).Elem()
}

type GetExperimentByNameResultOutput struct{ *pulumi.OutputState }

func (GetExperimentByNameResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetExperimentByNameResult)(nil)).Elem()
}

func (o GetExperimentByNameResultOutput) ToGetExperimentByNameResultOutput() GetExperimentByNameResultOutput {
	return o
}

func (o GetExperimentByNameResultOutput) ToGetExperimentByNameResultOutputWithContext(ctx context.Context) GetExperimentByNameResultOutput {
	return o
}

func (o GetExperimentByNameResultOutput) ArtifactLocation() pulumi.StringOutput {
	return o.ApplyT(func(v GetExperimentByNameResult) string { return v.ArtifactLocation }).(pulumi.StringOutput)
}

func (o GetExperimentByNameResultOutput) ExperimentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetExperimentByNameResult) string { return v.ExperimentId }).(pulumi.StringOutput)
}

func (o GetExperimentByNameResultOutput) LifecycleStage() pulumi.StringOutput {
	return o.ApplyT(func(v GetExperimentByNameResult) string { return v.LifecycleStage }).(pulumi.StringOutput)
}

func (o GetExperimentByNameResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetExperimentByNameResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetExperimentByNameResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetExperimentByNameResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetExperimentByNameResultOutput{})
}
