// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mlflow

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/tracking"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Searches MLflow experiments with an optional filter expression. Wraps [`experiments/search`](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-experiments).
//
// ## Example Usage
func SearchExperiments(ctx *pulumi.Context, args *SearchExperimentsArgs, opts ...pulumi.InvokeOption) (*SearchExperimentsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv SearchExperimentsResult
	err := ctx.Invoke("mlflow:index:searchExperiments", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type SearchExperimentsArgs struct {
	Filter     *string `pulumi:"filter"`
	MaxResults *int    `pulumi:"maxResults"`
}

type SearchExperimentsResult struct {
	Experiments []tracking.ExperimentResult `pulumi:"experiments"`
}

func SearchExperimentsOutput(ctx *pulumi.Context, args SearchExperimentsOutputArgs, opts ...pulumi.InvokeOption) SearchExperimentsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (SearchExperimentsResultOutput, error) {
			args := v.(SearchExperimentsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:index:searchExperiments", args, SearchExperimentsResultOutput{}, options).(SearchExperimentsResultOutput), nil
		}).(SearchExperimentsResultOutput)
}

type SearchExperimentsOutputArgs struct {
	Filter     pulumi.StringPtrInput `pulumi:"filter"`
	MaxResults pulumi.IntPtrInput    `pulumi:"maxResults"`
}

func (SearchExperimentsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchExperimentsArgs)(nil)).Elem()
}

type SearchExperimentsResultOutput struct{ *pulumi.OutputState }

func (SearchExperimentsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SearchExperimentsResult)(nil)).Elem()
}

func (o SearchExperimentsResultOutput) ToSearchExperimentsResultOutput() SearchExperimentsResultOutput {
	return o
}

func (o SearchExperimentsResultOutput) ToSearchExperimentsResultOutputWithContext(ctx context.Context) SearchExperimentsResultOutput {
	return o
}

func (o SearchExperimentsResultOutput) Experiments() tracking.ExperimentResultArrayOutput {
	return o.ApplyT(func(v SearchExperimentsResult) []tracking.ExperimentResult { return v.Experiments }).(tracking.ExperimentResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(SearchExperimentsResultOutput{})
}
