// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
func GetInsecureSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mlflow:insecureSkipVerify")
}

// Password for HTTP Basic authentication.
func GetPassword(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mlflow:password")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MLFLOW_TRACKING_PASSWORD"); d != nil {
		value = d.(string)
	}
	return value
}

// Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mlflow:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MLFLOW_TRACKING_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
func GetTrackingUri(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mlflow:trackingUri")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MLFLOW_TRACKING_URI"); d != nil {
		value = d.(string)
	}
	return value
}

// Username for HTTP Basic authentication against the MLflow tracking server.
func GetUsername(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mlflow:username")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MLFLOW_TRACKING_USERNAME"); d != nil {
		value = d.(string)
	}
	return value
}
