// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("mlflow");

/**
 * Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
 */
export declare const insecureSkipVerify: boolean | undefined;
Object.defineProperty(exports, "insecureSkipVerify", {
    get() {
        return __config.getObject<boolean>("insecureSkipVerify");
    },
    enumerable: true,
});

/**
 * Password for HTTP Basic authentication.
 */
export declare const password: string;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password") ?? (utilities.getEnv("MLFLOW_TRACKING_PASSWORD") || "");
    },
    enumerable: true,
});

/**
 * Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
 */
export declare const token: string;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? (utilities.getEnv("MLFLOW_TRACKING_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
 */
export declare const trackingUri: string;
Object.defineProperty(exports, "trackingUri", {
    get() {
        return __config.get("trackingUri") ?? (utilities.getEnv("MLFLOW_TRACKING_URI") || "");
    },
    enumerable: true,
});

/**
 * Username for HTTP Basic authentication against the MLflow tracking server.
 */
export declare const username: string;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username") ?? (utilities.getEnv("MLFLOW_TRACKING_USERNAME") || "");
    },
    enumerable: true,
});

