// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Returns the permission level a user has on an MLflow experiment.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getExperimentPermission(args: GetExperimentPermissionArgs, opts?: pulumi.InvokeOptions): Promise<GetExperimentPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:auth:getExperimentPermission", {
        "experimentId": args.experimentId,
        "username": args.username,
    }, opts);
}

export interface GetExperimentPermissionArgs {
    experimentId: string;
    username: string;
}

export interface GetExperimentPermissionResult {
    readonly permission: string;
}
/**
 * Returns the permission level a user has on an MLflow experiment.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getExperimentPermissionOutput(args: GetExperimentPermissionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetExperimentPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:auth:getExperimentPermission", {
        "experimentId": args.experimentId,
        "username": args.username,
    }, opts);
}

export interface GetExperimentPermissionOutputArgs {
    experimentId: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
