// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Returns the permission level a user has on an MLflow registered model.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getRegisteredModelPermission(args: GetRegisteredModelPermissionArgs, opts?: pulumi.InvokeOptions): Promise<GetRegisteredModelPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:auth:getRegisteredModelPermission", {
        "name": args.name,
        "username": args.username,
    }, opts);
}

export interface GetRegisteredModelPermissionArgs {
    name: string;
    username: string;
}

export interface GetRegisteredModelPermissionResult {
    readonly permission: string;
}
/**
 * Returns the permission level a user has on an MLflow registered model.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getRegisteredModelPermissionOutput(args: GetRegisteredModelPermissionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRegisteredModelPermissionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:auth:getRegisteredModelPermission", {
        "name": args.name,
        "username": args.username,
    }, opts);
}

export interface GetRegisteredModelPermissionOutputArgs {
    name: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
