// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Looks up an MLflow user by username, returning its admin flag and id.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:auth:getUser", {
        "username": args.username,
    }, opts);
}

export interface GetUserArgs {
    username: string;
}

export interface GetUserResult {
    readonly isAdmin: boolean;
    readonly userId: string;
    readonly username: string;
}
/**
 * Looks up an MLflow user by username, returning its admin flag and id.
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 */
export function getUserOutput(args: GetUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:auth:getUser", {
        "username": args.username,
    }, opts);
}

export interface GetUserOutputArgs {
    username: pulumi.Input<string>;
}
