// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ExperimentPermissionArgs } from "./experimentPermission";
export type ExperimentPermission = import("./experimentPermission").ExperimentPermission;
export const ExperimentPermission: typeof import("./experimentPermission").ExperimentPermission = null as any;
utilities.lazyLoad(exports, ["ExperimentPermission"], () => require("./experimentPermission"));

export { GetExperimentPermissionArgs, GetExperimentPermissionResult, GetExperimentPermissionOutputArgs } from "./getExperimentPermission";
export const getExperimentPermission: typeof import("./getExperimentPermission").getExperimentPermission = null as any;
export const getExperimentPermissionOutput: typeof import("./getExperimentPermission").getExperimentPermissionOutput = null as any;
utilities.lazyLoad(exports, ["getExperimentPermission","getExperimentPermissionOutput"], () => require("./getExperimentPermission"));

export { GetRegisteredModelPermissionArgs, GetRegisteredModelPermissionResult, GetRegisteredModelPermissionOutputArgs } from "./getRegisteredModelPermission";
export const getRegisteredModelPermission: typeof import("./getRegisteredModelPermission").getRegisteredModelPermission = null as any;
export const getRegisteredModelPermissionOutput: typeof import("./getRegisteredModelPermission").getRegisteredModelPermissionOutput = null as any;
utilities.lazyLoad(exports, ["getRegisteredModelPermission","getRegisteredModelPermissionOutput"], () => require("./getRegisteredModelPermission"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { RegisteredModelPermissionArgs } from "./registeredModelPermission";
export type RegisteredModelPermission = import("./registeredModelPermission").RegisteredModelPermission;
export const RegisteredModelPermission: typeof import("./registeredModelPermission").RegisteredModelPermission = null as any;
utilities.lazyLoad(exports, ["RegisteredModelPermission"], () => require("./registeredModelPermission"));

export { UserArgs } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mlflow:auth:ExperimentPermission":
                return new ExperimentPermission(name, <any>undefined, { urn })
            case "mlflow:auth:RegisteredModelPermission":
                return new RegisteredModelPermission(name, <any>undefined, { urn })
            case "mlflow:auth:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mlflow", "auth", _module)
