// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Grants a user a permission level on an MLflow registered model. Valid `permission` values are `READ`, `EDIT`, `MANAGE` and `NO_PERMISSIONS`; only `permission` can be updated in place (changing the model or user replaces the grant).
 *
 * > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Import an existing resource with its id:
 *
 * ```sh
 * $ pulumi import mlflow:auth:RegisteredModelPermission example <name>/<username>
 * ```
 */
export class RegisteredModelPermission extends pulumi.CustomResource {
    /**
     * Get an existing RegisteredModelPermission resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RegisteredModelPermission {
        return new RegisteredModelPermission(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mlflow:auth:RegisteredModelPermission';

    /**
     * Returns true if the given object is an instance of RegisteredModelPermission.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RegisteredModelPermission {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RegisteredModelPermission.__pulumiType;
    }

    /**
     * The registered model name. Changing this forces replacement.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
     */
    declare public readonly permission: pulumi.Output<string>;
    /**
     * The user to grant the permission to. Changing this forces replacement.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a RegisteredModelPermission resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RegisteredModelPermissionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.permission === undefined && !opts.urn) {
                throw new Error("Missing required property 'permission'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["permission"] = args?.permission;
            resourceInputs["username"] = args?.username;
        } else {
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["permission"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["name", "username"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(RegisteredModelPermission.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RegisteredModelPermission resource.
 */
export interface RegisteredModelPermissionArgs {
    /**
     * The registered model name. Changing this forces replacement.
     */
    name: pulumi.Input<string>;
    /**
     * The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
     */
    permission: pulumi.Input<string>;
    /**
     * The user to grant the permission to. Changing this forces replacement.
     */
    username: pulumi.Input<string>;
}
