# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'ExperimentResult',
]

@pulumi.output_type
class ExperimentResult(dict):
    def __init__(__self__, *,
                 artifact_location: _builtins.str,
                 experiment_id: _builtins.str,
                 lifecycle_stage: _builtins.str,
                 name: _builtins.str,
                 tags: Mapping[str, _builtins.str]):
        pulumi.set(__self__, "artifact_location", artifact_location)
        pulumi.set(__self__, "experiment_id", experiment_id)
        pulumi.set(__self__, "lifecycle_stage", lifecycle_stage)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="artifactLocation")
    def artifact_location(self) -> _builtins.str:
        return pulumi.get(self, "artifact_location")

    @_builtins.property
    @pulumi.getter(name="experimentId")
    def experiment_id(self) -> _builtins.str:
        return pulumi.get(self, "experiment_id")

    @_builtins.property
    @pulumi.getter(name="lifecycleStage")
    def lifecycle_stage(self) -> _builtins.str:
        return pulumi.get(self, "lifecycle_stage")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "tags")


