# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetLatestVersionsResult',
    'AwaitableGetLatestVersionsResult',
    'get_latest_versions',
    'get_latest_versions_output',
]

@pulumi.output_type
class GetLatestVersionsResult:
    def __init__(__self__, model_versions=None):
        if model_versions and not isinstance(model_versions, list):
            raise TypeError("Expected argument 'model_versions' to be a list")
        pulumi.set(__self__, "model_versions", model_versions)

    @_builtins.property
    @pulumi.getter(name="modelVersions")
    def model_versions(self) -> Sequence['outputs.ModelVersionResult']:
        return pulumi.get(self, "model_versions")


class AwaitableGetLatestVersionsResult(GetLatestVersionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetLatestVersionsResult(
            model_versions=self.model_versions)


def get_latest_versions(name: Optional[_builtins.str] = None,
                        stages: Optional[Sequence[_builtins.str]] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetLatestVersionsResult:
    """
    Returns the latest version of a registered model per stage (or overall).

    REST: `/api/2.0/mlflow/registered-models/get-latest-versions`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['stages'] = stages
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:registry:getLatestVersions', __args__, opts=opts, typ=GetLatestVersionsResult).value

    return AwaitableGetLatestVersionsResult(
        model_versions=pulumi.get(__ret__, 'model_versions'))
def get_latest_versions_output(name: pulumi.Input[Optional[_builtins.str]] = None,
                               stages: pulumi.Input[Optional[Optional[Sequence[_builtins.str]]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetLatestVersionsResult]:
    """
    Returns the latest version of a registered model per stage (or overall).

    REST: `/api/2.0/mlflow/registered-models/get-latest-versions`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['stages'] = stages
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:registry:getLatestVersions', __args__, opts=opts, typ=GetLatestVersionsResult)
    return __ret__.apply(lambda __response__: GetLatestVersionsResult(
        model_versions=pulumi.get(__response__, 'model_versions')))
