# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetModelVersionByAliasResult',
    'AwaitableGetModelVersionByAliasResult',
    'get_model_version_by_alias',
    'get_model_version_by_alias_output',
]

@pulumi.output_type
class GetModelVersionByAliasResult:
    def __init__(__self__, aliases=None, current_stage=None, description=None, name=None, run_id=None, source=None, status=None, tags=None, version=None):
        if aliases and not isinstance(aliases, list):
            raise TypeError("Expected argument 'aliases' to be a list")
        pulumi.set(__self__, "aliases", aliases)
        if current_stage and not isinstance(current_stage, str):
            raise TypeError("Expected argument 'current_stage' to be a str")
        pulumi.set(__self__, "current_stage", current_stage)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if run_id and not isinstance(run_id, str):
            raise TypeError("Expected argument 'run_id' to be a str")
        pulumi.set(__self__, "run_id", run_id)
        if source and not isinstance(source, str):
            raise TypeError("Expected argument 'source' to be a str")
        pulumi.set(__self__, "source", source)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if tags and not isinstance(tags, dict):
            raise TypeError("Expected argument 'tags' to be a dict")
        pulumi.set(__self__, "tags", tags)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def aliases(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "aliases")

    @_builtins.property
    @pulumi.getter(name="currentStage")
    def current_stage(self) -> _builtins.str:
        return pulumi.get(self, "current_stage")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="runId")
    def run_id(self) -> _builtins.str:
        return pulumi.get(self, "run_id")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")


class AwaitableGetModelVersionByAliasResult(GetModelVersionByAliasResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetModelVersionByAliasResult(
            aliases=self.aliases,
            current_stage=self.current_stage,
            description=self.description,
            name=self.name,
            run_id=self.run_id,
            source=self.source,
            status=self.status,
            tags=self.tags,
            version=self.version)


def get_model_version_by_alias(alias: Optional[_builtins.str] = None,
                               name: Optional[_builtins.str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetModelVersionByAliasResult:
    """
    Resolves an alias on a registered model to the model version it currently points at — useful for reading which version is, for example, `champion`.

    REST: `/api/2.0/mlflow/registered-models/alias` (get).

    ## Example Usage
    """
    __args__ = dict()
    __args__['alias'] = alias
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:registry:getModelVersionByAlias', __args__, opts=opts, typ=GetModelVersionByAliasResult).value

    return AwaitableGetModelVersionByAliasResult(
        aliases=pulumi.get(__ret__, 'aliases'),
        current_stage=pulumi.get(__ret__, 'current_stage'),
        description=pulumi.get(__ret__, 'description'),
        name=pulumi.get(__ret__, 'name'),
        run_id=pulumi.get(__ret__, 'run_id'),
        source=pulumi.get(__ret__, 'source'),
        status=pulumi.get(__ret__, 'status'),
        tags=pulumi.get(__ret__, 'tags'),
        version=pulumi.get(__ret__, 'version'))
def get_model_version_by_alias_output(alias: pulumi.Input[Optional[_builtins.str]] = None,
                                      name: pulumi.Input[Optional[_builtins.str]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetModelVersionByAliasResult]:
    """
    Resolves an alias on a registered model to the model version it currently points at — useful for reading which version is, for example, `champion`.

    REST: `/api/2.0/mlflow/registered-models/alias` (get).

    ## Example Usage
    """
    __args__ = dict()
    __args__['alias'] = alias
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:registry:getModelVersionByAlias', __args__, opts=opts, typ=GetModelVersionByAliasResult)
    return __ret__.apply(lambda __response__: GetModelVersionByAliasResult(
        aliases=pulumi.get(__response__, 'aliases'),
        current_stage=pulumi.get(__response__, 'current_stage'),
        description=pulumi.get(__response__, 'description'),
        name=pulumi.get(__response__, 'name'),
        run_id=pulumi.get(__response__, 'run_id'),
        source=pulumi.get(__response__, 'source'),
        status=pulumi.get(__response__, 'status'),
        tags=pulumi.get(__response__, 'tags'),
        version=pulumi.get(__response__, 'version')))
