# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetModelVersionDownloadUriResult',
    'AwaitableGetModelVersionDownloadUriResult',
    'get_model_version_download_uri',
    'get_model_version_download_uri_output',
]

@pulumi.output_type
class GetModelVersionDownloadUriResult:
    def __init__(__self__, artifact_uri=None):
        if artifact_uri and not isinstance(artifact_uri, str):
            raise TypeError("Expected argument 'artifact_uri' to be a str")
        pulumi.set(__self__, "artifact_uri", artifact_uri)

    @_builtins.property
    @pulumi.getter(name="artifactUri")
    def artifact_uri(self) -> _builtins.str:
        return pulumi.get(self, "artifact_uri")


class AwaitableGetModelVersionDownloadUriResult(GetModelVersionDownloadUriResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetModelVersionDownloadUriResult(
            artifact_uri=self.artifact_uri)


def get_model_version_download_uri(name: Optional[_builtins.str] = None,
                                   version: Optional[_builtins.str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetModelVersionDownloadUriResult:
    """
    Returns the artifact download URI for a model version.

    REST: `/api/2.0/mlflow/model-versions/get-download-uri`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['version'] = version
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:registry:getModelVersionDownloadUri', __args__, opts=opts, typ=GetModelVersionDownloadUriResult).value

    return AwaitableGetModelVersionDownloadUriResult(
        artifact_uri=pulumi.get(__ret__, 'artifact_uri'))
def get_model_version_download_uri_output(name: pulumi.Input[Optional[_builtins.str]] = None,
                                          version: pulumi.Input[Optional[_builtins.str]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetModelVersionDownloadUriResult]:
    """
    Returns the artifact download URI for a model version.

    REST: `/api/2.0/mlflow/model-versions/get-download-uri`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['version'] = version
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:registry:getModelVersionDownloadUri', __args__, opts=opts, typ=GetModelVersionDownloadUriResult)
    return __ret__.apply(lambda __response__: GetModelVersionDownloadUriResult(
        artifact_uri=pulumi.get(__response__, 'artifact_uri')))
