# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ModelVersionArgs', 'ModelVersion']

@pulumi.input_type
class ModelVersionArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 source: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 run_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_link: pulumi.Input[Optional[_builtins.str]] = None,
                 stage: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a ModelVersion resource.

        :param pulumi.Input[_builtins.str] name: Parent registered model name. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] source: URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
        :param pulumi.Input[_builtins.str] description: Optional human-readable description. Updated in place.
        :param pulumi.Input[_builtins.str] run_id: Optional MLflow run that produced the model. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] run_link: Optional link to the source run. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] stage: Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Optional key/value metadata tags. Synced in place.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "source", source)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if run_id is not None:
            pulumi.set(__self__, "run_id", run_id)
        if run_link is not None:
            pulumi.set(__self__, "run_link", run_link)
        if stage is not None:
            warnings.warn("""Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.""", DeprecationWarning)
            pulumi.log.warn("""stage is deprecated: Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.""")
        if stage is not None:
            pulumi.set(__self__, "stage", stage)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Parent registered model name. Changing it replaces the version.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[_builtins.str]:
        """
        URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional human-readable description. Updated in place.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="runId")
    def run_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional MLflow run that produced the model. Changing it replaces the version.
        """
        return pulumi.get(self, "run_id")

    @run_id.setter
    def run_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "run_id", value)

    @_builtins.property
    @pulumi.getter(name="runLink")
    def run_link(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional link to the source run. Changing it replaces the version.
        """
        return pulumi.get(self, "run_link")

    @run_link.setter
    def run_link(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "run_link", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.""")
    def stage(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
        """
        return pulumi.get(self, "stage")

    @stage.setter
    def stage(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "stage", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Optional key/value metadata tags. Synced in place.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("mlflow:registry:ModelVersion")
class ModelVersion(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 run_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_link: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 stage: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Manages a version of a [registered model](https://mlflow.org/docs/latest/ml/model-registry/) — an immutable snapshot of a model's artifacts.

        The `source`, `runId` and `runLink` are set once: changing any of them replaces the version. Only `description` and `tags` update in place. On create, the provider waits until the version's status is `READY`.

        > **Note:** `stage` (None/Staging/Production/Archived) is **deprecated in MLflow 3**. Prefer [`RegisteredModelAlias`](/registry/registeredmodelalias) to drive deployments. Setting `stage` against a 3.x server emits a warning.

        REST endpoints: `/api/2.0/mlflow/model-versions/{create,get,update,delete,set-tag,delete-tag,transition-stage}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-modelversion).

        ## Example Usage

        ## Import

        Model versions can be imported using `<model-name>/<version>`:

        ```sh
        pulumi import mlflow:registry:ModelVersion fraud-v1 fraud-detector/1
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Optional human-readable description. Updated in place.
        :param pulumi.Input[_builtins.str] name: Parent registered model name. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] run_id: Optional MLflow run that produced the model. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] run_link: Optional link to the source run. Changing it replaces the version.
        :param pulumi.Input[_builtins.str] source: URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
        :param pulumi.Input[_builtins.str] stage: Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Optional key/value metadata tags. Synced in place.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ModelVersionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a version of a [registered model](https://mlflow.org/docs/latest/ml/model-registry/) — an immutable snapshot of a model's artifacts.

        The `source`, `runId` and `runLink` are set once: changing any of them replaces the version. Only `description` and `tags` update in place. On create, the provider waits until the version's status is `READY`.

        > **Note:** `stage` (None/Staging/Production/Archived) is **deprecated in MLflow 3**. Prefer [`RegisteredModelAlias`](/registry/registeredmodelalias) to drive deployments. Setting `stage` against a 3.x server emits a warning.

        REST endpoints: `/api/2.0/mlflow/model-versions/{create,get,update,delete,set-tag,delete-tag,transition-stage}` — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#create-modelversion).

        ## Example Usage

        ## Import

        Model versions can be imported using `<model-name>/<version>`:

        ```sh
        pulumi import mlflow:registry:ModelVersion fraud-v1 fraud-detector/1
        ```


        :param str resource_name: The name of the resource.
        :param ModelVersionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ModelVersionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 run_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_link: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 stage: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ModelVersionArgs.__new__(ModelVersionArgs)

            __props__.__dict__["description"] = description
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["run_id"] = run_id
            __props__.__dict__["run_link"] = run_link
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["stage"] = stage
            __props__.__dict__["tags"] = tags
            __props__.__dict__["aliases"] = None
            __props__.__dict__["creation_timestamp"] = None
            __props__.__dict__["current_stage"] = None
            __props__.__dict__["last_updated_timestamp"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["version"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["name", "runId", "runLink", "source"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(ModelVersion, __self__).__init__(
            'mlflow:registry:ModelVersion',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ModelVersion':
        """
        Get an existing ModelVersion resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ModelVersionArgs.__new__(ModelVersionArgs)

        __props__.__dict__["aliases"] = None
        __props__.__dict__["creation_timestamp"] = None
        __props__.__dict__["current_stage"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["last_updated_timestamp"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["run_id"] = None
        __props__.__dict__["run_link"] = None
        __props__.__dict__["source"] = None
        __props__.__dict__["stage"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["version"] = None
        return ModelVersion(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def aliases(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Aliases currently pointing at this version.
        """
        return pulumi.get(self, "aliases")

    @_builtins.property
    @pulumi.getter(name="creationTimestamp")
    def creation_timestamp(self) -> pulumi.Output[_builtins.int]:
        """
        Creation time, in epoch milliseconds.
        """
        return pulumi.get(self, "creation_timestamp")

    @_builtins.property
    @pulumi.getter(name="currentStage")
    def current_stage(self) -> pulumi.Output[_builtins.str]:
        """
        The version's current stage (deprecated in MLflow 3; prefer aliases).
        """
        return pulumi.get(self, "current_stage")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional human-readable description. Updated in place.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedTimestamp")
    def last_updated_timestamp(self) -> pulumi.Output[_builtins.int]:
        """
        Last update time, in epoch milliseconds.
        """
        return pulumi.get(self, "last_updated_timestamp")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Parent registered model name. Changing it replaces the version.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="runId")
    def run_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional MLflow run that produced the model. Changing it replaces the version.
        """
        return pulumi.get(self, "run_id")

    @_builtins.property
    @pulumi.getter(name="runLink")
    def run_link(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional link to the source run. Changing it replaces the version.
        """
        return pulumi.get(self, "run_link")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        """
        URI of the model artifacts (e.g. an s3:// path). Set once; changing it replaces the version.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Model stages are deprecated in MLflow 3. Use RegisteredModelAlias instead.""")
    def stage(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Deprecated model stage (None/Staging/Production/Archived). Prefer RegisteredModelAlias; setting this on MLflow 3 emits a warning.
        """
        return pulumi.get(self, "stage")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Registration status; the provider waits for READY on create.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Optional key/value metadata tags. Synced in place.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Server-assigned version number (immutable).
        """
        return pulumi.get(self, "version")

