# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'ModelVersionResult',
    'RegisteredModelResult',
]

@pulumi.output_type
class ModelVersionResult(dict):
    def __init__(__self__, *,
                 aliases: Sequence[_builtins.str],
                 current_stage: _builtins.str,
                 description: _builtins.str,
                 name: _builtins.str,
                 run_id: _builtins.str,
                 source: _builtins.str,
                 status: _builtins.str,
                 tags: Mapping[str, _builtins.str],
                 version: _builtins.str):
        pulumi.set(__self__, "aliases", aliases)
        pulumi.set(__self__, "current_stage", current_stage)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "run_id", run_id)
        pulumi.set(__self__, "source", source)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "tags", tags)
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def aliases(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "aliases")

    @_builtins.property
    @pulumi.getter(name="currentStage")
    def current_stage(self) -> _builtins.str:
        return pulumi.get(self, "current_stage")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="runId")
    def run_id(self) -> _builtins.str:
        return pulumi.get(self, "run_id")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")


@pulumi.output_type
class RegisteredModelResult(dict):
    def __init__(__self__, *,
                 creation_timestamp: _builtins.int,
                 description: _builtins.str,
                 last_updated_timestamp: _builtins.int,
                 name: _builtins.str,
                 tags: Mapping[str, _builtins.str]):
        pulumi.set(__self__, "creation_timestamp", creation_timestamp)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "last_updated_timestamp", last_updated_timestamp)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="creationTimestamp")
    def creation_timestamp(self) -> _builtins.int:
        return pulumi.get(self, "creation_timestamp")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedTimestamp")
    def last_updated_timestamp(self) -> _builtins.int:
        return pulumi.get(self, "last_updated_timestamp")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "tags")


