# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['RegisteredModelAliasArgs', 'RegisteredModelAlias']

@pulumi.input_type
class RegisteredModelAliasArgs:
    def __init__(__self__, *,
                 alias: pulumi.Input[_builtins.str],
                 model_name: pulumi.Input[_builtins.str],
                 version: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a RegisteredModelAlias resource.

        :param pulumi.Input[_builtins.str] alias: Alias name, e.g. "champion". Changing it replaces the resource.
        :param pulumi.Input[_builtins.str] model_name: Registered model the alias belongs to. Changing it replaces the resource.
        :param pulumi.Input[_builtins.str] version: Model version the alias points at. Updating it re-points the alias in place.
        """
        pulumi.set(__self__, "alias", alias)
        pulumi.set(__self__, "model_name", model_name)
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> pulumi.Input[_builtins.str]:
        """
        Alias name, e.g. "champion". Changing it replaces the resource.
        """
        return pulumi.get(self, "alias")

    @alias.setter
    def alias(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "alias", value)

    @_builtins.property
    @pulumi.getter(name="modelName")
    def model_name(self) -> pulumi.Input[_builtins.str]:
        """
        Registered model the alias belongs to. Changing it replaces the resource.
        """
        return pulumi.get(self, "model_name")

    @model_name.setter
    def model_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "model_name", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Input[_builtins.str]:
        """
        Model version the alias points at. Updating it re-points the alias in place.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "version", value)


@pulumi.type_token("mlflow:registry:RegisteredModelAlias")
class RegisteredModelAlias(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alias: pulumi.Input[Optional[_builtins.str]] = None,
                 model_name: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a named [alias](https://mlflow.org/docs/latest/ml/model-registry/#deploy-and-organize-models-with-aliases-and-tags) on a registered model that points at a specific version (for example `champion` → version 3).

        Aliases are mutable pointers and are the **recommended** way to drive deployments; they supersede the deprecated model *stages*. `version` is updatable — changing it re-points the alias to a different version — while `modelName` and `alias` changes replace the resource.

        REST endpoints: `/api/2.0/mlflow/registered-models/alias` (set/delete/get) — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#set-registered-model-alias).

        ## Example Usage

        ## Import

        Aliases can be imported using `<model-name>/<alias>`:

        ```sh
        pulumi import mlflow:registry:RegisteredModelAlias champion fraud-detector/champion
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alias: Alias name, e.g. "champion". Changing it replaces the resource.
        :param pulumi.Input[_builtins.str] model_name: Registered model the alias belongs to. Changing it replaces the resource.
        :param pulumi.Input[_builtins.str] version: Model version the alias points at. Updating it re-points the alias in place.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RegisteredModelAliasArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a named [alias](https://mlflow.org/docs/latest/ml/model-registry/#deploy-and-organize-models-with-aliases-and-tags) on a registered model that points at a specific version (for example `champion` → version 3).

        Aliases are mutable pointers and are the **recommended** way to drive deployments; they supersede the deprecated model *stages*. `version` is updatable — changing it re-points the alias to a different version — while `modelName` and `alias` changes replace the resource.

        REST endpoints: `/api/2.0/mlflow/registered-models/alias` (set/delete/get) — see the [MLflow REST API](https://mlflow.org/docs/latest/api_reference/rest-api.html#set-registered-model-alias).

        ## Example Usage

        ## Import

        Aliases can be imported using `<model-name>/<alias>`:

        ```sh
        pulumi import mlflow:registry:RegisteredModelAlias champion fraud-detector/champion
        ```


        :param str resource_name: The name of the resource.
        :param RegisteredModelAliasArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RegisteredModelAliasArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alias: pulumi.Input[Optional[_builtins.str]] = None,
                 model_name: pulumi.Input[Optional[_builtins.str]] = None,
                 version: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RegisteredModelAliasArgs.__new__(RegisteredModelAliasArgs)

            if alias is None and not opts.urn:
                raise TypeError("Missing required property 'alias'")
            __props__.__dict__["alias"] = alias
            if model_name is None and not opts.urn:
                raise TypeError("Missing required property 'model_name'")
            __props__.__dict__["model_name"] = model_name
            if version is None and not opts.urn:
                raise TypeError("Missing required property 'version'")
            __props__.__dict__["version"] = version
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["alias", "modelName"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(RegisteredModelAlias, __self__).__init__(
            'mlflow:registry:RegisteredModelAlias',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'RegisteredModelAlias':
        """
        Get an existing RegisteredModelAlias resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = RegisteredModelAliasArgs.__new__(RegisteredModelAliasArgs)

        __props__.__dict__["alias"] = None
        __props__.__dict__["model_name"] = None
        __props__.__dict__["version"] = None
        return RegisteredModelAlias(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> pulumi.Output[_builtins.str]:
        """
        Alias name, e.g. "champion". Changing it replaces the resource.
        """
        return pulumi.get(self, "alias")

    @_builtins.property
    @pulumi.getter(name="modelName")
    def model_name(self) -> pulumi.Output[_builtins.str]:
        """
        Registered model the alias belongs to. Changing it replaces the resource.
        """
        return pulumi.get(self, "model_name")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.str]:
        """
        Model version the alias points at. Updating it re-points the alias in place.
        """
        return pulumi.get(self, "version")

