# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'SearchRegisteredModelsResult',
    'AwaitableSearchRegisteredModelsResult',
    'search_registered_models',
    'search_registered_models_output',
]

@pulumi.output_type
class SearchRegisteredModelsResult:
    def __init__(__self__, registered_models=None):
        if registered_models and not isinstance(registered_models, list):
            raise TypeError("Expected argument 'registered_models' to be a list")
        pulumi.set(__self__, "registered_models", registered_models)

    @_builtins.property
    @pulumi.getter(name="registeredModels")
    def registered_models(self) -> Sequence['outputs.RegisteredModelResult']:
        return pulumi.get(self, "registered_models")


class AwaitableSearchRegisteredModelsResult(SearchRegisteredModelsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return SearchRegisteredModelsResult(
            registered_models=self.registered_models)


def search_registered_models(filter: Optional[_builtins.str] = None,
                             max_results: Optional[_builtins.int] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableSearchRegisteredModelsResult:
    """
    Searches registered models with an optional MLflow [filter string](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-registeredmodels).

    REST: `/api/2.0/mlflow/registered-models/search`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['maxResults'] = max_results
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:registry:searchRegisteredModels', __args__, opts=opts, typ=SearchRegisteredModelsResult).value

    return AwaitableSearchRegisteredModelsResult(
        registered_models=pulumi.get(__ret__, 'registered_models'))
def search_registered_models_output(filter: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                    max_results: pulumi.Input[Optional[Optional[_builtins.int]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[SearchRegisteredModelsResult]:
    """
    Searches registered models with an optional MLflow [filter string](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-registeredmodels).

    REST: `/api/2.0/mlflow/registered-models/search`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['maxResults'] = max_results
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:registry:searchRegisteredModels', __args__, opts=opts, typ=SearchRegisteredModelsResult)
    return __ret__.apply(lambda __response__: SearchRegisteredModelsResult(
        registered_models=pulumi.get(__response__, 'registered_models')))
