# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'SearchModelVersionsResult',
    'AwaitableSearchModelVersionsResult',
    'search_model_versions',
    'search_model_versions_output',
]

@pulumi.output_type
class SearchModelVersionsResult:
    def __init__(__self__, model_versions=None):
        if model_versions and not isinstance(model_versions, list):
            raise TypeError("Expected argument 'model_versions' to be a list")
        pulumi.set(__self__, "model_versions", model_versions)

    @_builtins.property
    @pulumi.getter(name="modelVersions")
    def model_versions(self) -> Sequence['outputs.ModelVersionResult']:
        return pulumi.get(self, "model_versions")


class AwaitableSearchModelVersionsResult(SearchModelVersionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return SearchModelVersionsResult(
            model_versions=self.model_versions)


def search_model_versions(filter: Optional[_builtins.str] = None,
                          max_results: Optional[_builtins.int] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableSearchModelVersionsResult:
    """
    Searches model versions with an optional MLflow filter string.

    REST: `/api/2.0/mlflow/model-versions/search`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['maxResults'] = max_results
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mlflow:registry:searchModelVersions', __args__, opts=opts, typ=SearchModelVersionsResult).value

    return AwaitableSearchModelVersionsResult(
        model_versions=pulumi.get(__ret__, 'model_versions'))
def search_model_versions_output(filter: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 max_results: pulumi.Input[Optional[Optional[_builtins.int]]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[SearchModelVersionsResult]:
    """
    Searches model versions with an optional MLflow filter string.

    REST: `/api/2.0/mlflow/model-versions/search`.

    ## Example Usage
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['maxResults'] = max_results
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mlflow:registry:searchModelVersions', __args__, opts=opts, typ=SearchModelVersionsResult)
    return __ret__.apply(lambda __response__: SearchModelVersionsResult(
        model_versions=pulumi.get(__response__, 'model_versions')))
