// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package auth

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Grants a user a permission level on an MLflow experiment. Valid `permission` values are `READ`, `EDIT`, `MANAGE` and `NO_PERMISSIONS`; only `permission` can be updated in place (changing the experiment or user replaces the grant).
//
// > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
//
// ## Example Usage
//
// ## Import
//
// Import an existing resource with its id:
//
// ```sh
// $ pulumi import mlflow:auth:ExperimentPermission example <experimentId>/<username>
// ```
type ExperimentPermission struct {
	pulumi.CustomResourceState

	// The experiment id. Changing this forces replacement.
	ExperimentId pulumi.StringOutput `pulumi:"experimentId"`
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission pulumi.StringOutput `pulumi:"permission"`
	// The user to grant the permission to. Changing this forces replacement.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewExperimentPermission registers a new resource with the given unique name, arguments, and options.
func NewExperimentPermission(ctx *pulumi.Context,
	name string, args *ExperimentPermissionArgs, opts ...pulumi.ResourceOption) (*ExperimentPermission, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ExperimentId == nil {
		return nil, errors.New("invalid value for required argument 'ExperimentId'")
	}
	if args.Permission == nil {
		return nil, errors.New("invalid value for required argument 'Permission'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"experimentId",
		"username",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ExperimentPermission
	err := ctx.RegisterResource("mlflow:auth:ExperimentPermission", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetExperimentPermission gets an existing ExperimentPermission resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetExperimentPermission(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ExperimentPermissionState, opts ...pulumi.ResourceOption) (*ExperimentPermission, error) {
	var resource ExperimentPermission
	err := ctx.ReadResource("mlflow:auth:ExperimentPermission", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ExperimentPermission resources.
type experimentPermissionState struct {
}

type ExperimentPermissionState struct {
}

func (ExperimentPermissionState) ElementType() reflect.Type {
	return reflect.TypeOf((*experimentPermissionState)(nil)).Elem()
}

type experimentPermissionArgs struct {
	// The experiment id. Changing this forces replacement.
	ExperimentId string `pulumi:"experimentId"`
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission string `pulumi:"permission"`
	// The user to grant the permission to. Changing this forces replacement.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a ExperimentPermission resource.
type ExperimentPermissionArgs struct {
	// The experiment id. Changing this forces replacement.
	ExperimentId pulumi.StringInput
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission pulumi.StringInput
	// The user to grant the permission to. Changing this forces replacement.
	Username pulumi.StringInput
}

func (ExperimentPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*experimentPermissionArgs)(nil)).Elem()
}

type ExperimentPermissionInput interface {
	pulumi.Input

	ToExperimentPermissionOutput() ExperimentPermissionOutput
	ToExperimentPermissionOutputWithContext(ctx context.Context) ExperimentPermissionOutput
}

func (*ExperimentPermission) ElementType() reflect.Type {
	return reflect.TypeOf((**ExperimentPermission)(nil)).Elem()
}

func (i *ExperimentPermission) ToExperimentPermissionOutput() ExperimentPermissionOutput {
	return i.ToExperimentPermissionOutputWithContext(context.Background())
}

func (i *ExperimentPermission) ToExperimentPermissionOutputWithContext(ctx context.Context) ExperimentPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ExperimentPermissionOutput)
}

// ExperimentPermissionArrayInput is an input type that accepts ExperimentPermissionArray and ExperimentPermissionArrayOutput values.
// You can construct a concrete instance of `ExperimentPermissionArrayInput` via:
//
//	ExperimentPermissionArray{ ExperimentPermissionArgs{...} }
type ExperimentPermissionArrayInput interface {
	pulumi.Input

	ToExperimentPermissionArrayOutput() ExperimentPermissionArrayOutput
	ToExperimentPermissionArrayOutputWithContext(context.Context) ExperimentPermissionArrayOutput
}

type ExperimentPermissionArray []ExperimentPermissionInput

func (ExperimentPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ExperimentPermission)(nil)).Elem()
}

func (i ExperimentPermissionArray) ToExperimentPermissionArrayOutput() ExperimentPermissionArrayOutput {
	return i.ToExperimentPermissionArrayOutputWithContext(context.Background())
}

func (i ExperimentPermissionArray) ToExperimentPermissionArrayOutputWithContext(ctx context.Context) ExperimentPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ExperimentPermissionArrayOutput)
}

// ExperimentPermissionMapInput is an input type that accepts ExperimentPermissionMap and ExperimentPermissionMapOutput values.
// You can construct a concrete instance of `ExperimentPermissionMapInput` via:
//
//	ExperimentPermissionMap{ "key": ExperimentPermissionArgs{...} }
type ExperimentPermissionMapInput interface {
	pulumi.Input

	ToExperimentPermissionMapOutput() ExperimentPermissionMapOutput
	ToExperimentPermissionMapOutputWithContext(context.Context) ExperimentPermissionMapOutput
}

type ExperimentPermissionMap map[string]ExperimentPermissionInput

func (ExperimentPermissionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ExperimentPermission)(nil)).Elem()
}

func (i ExperimentPermissionMap) ToExperimentPermissionMapOutput() ExperimentPermissionMapOutput {
	return i.ToExperimentPermissionMapOutputWithContext(context.Background())
}

func (i ExperimentPermissionMap) ToExperimentPermissionMapOutputWithContext(ctx context.Context) ExperimentPermissionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ExperimentPermissionMapOutput)
}

type ExperimentPermissionOutput struct{ *pulumi.OutputState }

func (ExperimentPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ExperimentPermission)(nil)).Elem()
}

func (o ExperimentPermissionOutput) ToExperimentPermissionOutput() ExperimentPermissionOutput {
	return o
}

func (o ExperimentPermissionOutput) ToExperimentPermissionOutputWithContext(ctx context.Context) ExperimentPermissionOutput {
	return o
}

// The experiment id. Changing this forces replacement.
func (o ExperimentPermissionOutput) ExperimentId() pulumi.StringOutput {
	return o.ApplyT(func(v *ExperimentPermission) pulumi.StringOutput { return v.ExperimentId }).(pulumi.StringOutput)
}

// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
func (o ExperimentPermissionOutput) Permission() pulumi.StringOutput {
	return o.ApplyT(func(v *ExperimentPermission) pulumi.StringOutput { return v.Permission }).(pulumi.StringOutput)
}

// The user to grant the permission to. Changing this forces replacement.
func (o ExperimentPermissionOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *ExperimentPermission) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type ExperimentPermissionArrayOutput struct{ *pulumi.OutputState }

func (ExperimentPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ExperimentPermission)(nil)).Elem()
}

func (o ExperimentPermissionArrayOutput) ToExperimentPermissionArrayOutput() ExperimentPermissionArrayOutput {
	return o
}

func (o ExperimentPermissionArrayOutput) ToExperimentPermissionArrayOutputWithContext(ctx context.Context) ExperimentPermissionArrayOutput {
	return o
}

func (o ExperimentPermissionArrayOutput) Index(i pulumi.IntInput) ExperimentPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ExperimentPermission {
		return vs[0].([]*ExperimentPermission)[vs[1].(int)]
	}).(ExperimentPermissionOutput)
}

type ExperimentPermissionMapOutput struct{ *pulumi.OutputState }

func (ExperimentPermissionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ExperimentPermission)(nil)).Elem()
}

func (o ExperimentPermissionMapOutput) ToExperimentPermissionMapOutput() ExperimentPermissionMapOutput {
	return o
}

func (o ExperimentPermissionMapOutput) ToExperimentPermissionMapOutputWithContext(ctx context.Context) ExperimentPermissionMapOutput {
	return o
}

func (o ExperimentPermissionMapOutput) MapIndex(k pulumi.StringInput) ExperimentPermissionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ExperimentPermission {
		return vs[0].(map[string]*ExperimentPermission)[vs[1].(string)]
	}).(ExperimentPermissionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ExperimentPermissionInput)(nil)).Elem(), &ExperimentPermission{})
	pulumi.RegisterInputType(reflect.TypeOf((*ExperimentPermissionArrayInput)(nil)).Elem(), ExperimentPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ExperimentPermissionMapInput)(nil)).Elem(), ExperimentPermissionMap{})
	pulumi.RegisterOutputType(ExperimentPermissionOutput{})
	pulumi.RegisterOutputType(ExperimentPermissionArrayOutput{})
	pulumi.RegisterOutputType(ExperimentPermissionMapOutput{})
}
