// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package auth

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the permission level a user has on an MLflow experiment.
//
// > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
//
// ## Example Usage
func LookupExperimentPermission(ctx *pulumi.Context, args *LookupExperimentPermissionArgs, opts ...pulumi.InvokeOption) (*LookupExperimentPermissionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupExperimentPermissionResult
	err := ctx.Invoke("mlflow:auth:getExperimentPermission", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupExperimentPermissionArgs struct {
	ExperimentId string `pulumi:"experimentId"`
	Username     string `pulumi:"username"`
}

type LookupExperimentPermissionResult struct {
	Permission string `pulumi:"permission"`
}

func LookupExperimentPermissionOutput(ctx *pulumi.Context, args LookupExperimentPermissionOutputArgs, opts ...pulumi.InvokeOption) LookupExperimentPermissionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupExperimentPermissionResultOutput, error) {
			args := v.(LookupExperimentPermissionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:auth:getExperimentPermission", args, LookupExperimentPermissionResultOutput{}, options).(LookupExperimentPermissionResultOutput), nil
		}).(LookupExperimentPermissionResultOutput)
}

type LookupExperimentPermissionOutputArgs struct {
	ExperimentId pulumi.StringInput `pulumi:"experimentId"`
	Username     pulumi.StringInput `pulumi:"username"`
}

func (LookupExperimentPermissionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExperimentPermissionArgs)(nil)).Elem()
}

type LookupExperimentPermissionResultOutput struct{ *pulumi.OutputState }

func (LookupExperimentPermissionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupExperimentPermissionResult)(nil)).Elem()
}

func (o LookupExperimentPermissionResultOutput) ToLookupExperimentPermissionResultOutput() LookupExperimentPermissionResultOutput {
	return o
}

func (o LookupExperimentPermissionResultOutput) ToLookupExperimentPermissionResultOutputWithContext(ctx context.Context) LookupExperimentPermissionResultOutput {
	return o
}

func (o LookupExperimentPermissionResultOutput) Permission() pulumi.StringOutput {
	return o.ApplyT(func(v LookupExperimentPermissionResult) string { return v.Permission }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupExperimentPermissionResultOutput{})
}
