// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package auth

import (
	"context"
	"reflect"

	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the permission level a user has on an MLflow registered model.
//
// > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
//
// ## Example Usage
func LookupRegisteredModelPermission(ctx *pulumi.Context, args *LookupRegisteredModelPermissionArgs, opts ...pulumi.InvokeOption) (*LookupRegisteredModelPermissionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRegisteredModelPermissionResult
	err := ctx.Invoke("mlflow:auth:getRegisteredModelPermission", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupRegisteredModelPermissionArgs struct {
	Name     string `pulumi:"name"`
	Username string `pulumi:"username"`
}

type LookupRegisteredModelPermissionResult struct {
	Permission string `pulumi:"permission"`
}

func LookupRegisteredModelPermissionOutput(ctx *pulumi.Context, args LookupRegisteredModelPermissionOutputArgs, opts ...pulumi.InvokeOption) LookupRegisteredModelPermissionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRegisteredModelPermissionResultOutput, error) {
			args := v.(LookupRegisteredModelPermissionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mlflow:auth:getRegisteredModelPermission", args, LookupRegisteredModelPermissionResultOutput{}, options).(LookupRegisteredModelPermissionResultOutput), nil
		}).(LookupRegisteredModelPermissionResultOutput)
}

type LookupRegisteredModelPermissionOutputArgs struct {
	Name     pulumi.StringInput `pulumi:"name"`
	Username pulumi.StringInput `pulumi:"username"`
}

func (LookupRegisteredModelPermissionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegisteredModelPermissionArgs)(nil)).Elem()
}

type LookupRegisteredModelPermissionResultOutput struct{ *pulumi.OutputState }

func (LookupRegisteredModelPermissionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegisteredModelPermissionResult)(nil)).Elem()
}

func (o LookupRegisteredModelPermissionResultOutput) ToLookupRegisteredModelPermissionResultOutput() LookupRegisteredModelPermissionResultOutput {
	return o
}

func (o LookupRegisteredModelPermissionResultOutput) ToLookupRegisteredModelPermissionResultOutputWithContext(ctx context.Context) LookupRegisteredModelPermissionResultOutput {
	return o
}

func (o LookupRegisteredModelPermissionResultOutput) Permission() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRegisteredModelPermissionResult) string { return v.Permission }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRegisteredModelPermissionResultOutput{})
}
