// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package auth

import (
	"context"
	"reflect"

	"errors"
	"github.com/Baubap/pulumi-mlflow/sdk/go/mlflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Grants a user a permission level on an MLflow registered model. Valid `permission` values are `READ`, `EDIT`, `MANAGE` and `NO_PERMISSIONS`; only `permission` can be updated in place (changing the model or user replaces the grant).
//
// > **Requires the MLflow auth app.** These resources call the [MLflow authentication REST API](https://mlflow.org/docs/latest/auth/rest-api.html), which is only available when the tracking server runs with the `mlflow.server.auth` app enabled (e.g. `mlflow server --app-name basic-auth`).
//
// ## Example Usage
//
// ## Import
//
// Import an existing resource with its id:
//
// ```sh
// $ pulumi import mlflow:auth:RegisteredModelPermission example <name>/<username>
// ```
type RegisteredModelPermission struct {
	pulumi.CustomResourceState

	// The registered model name. Changing this forces replacement.
	Name pulumi.StringOutput `pulumi:"name"`
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission pulumi.StringOutput `pulumi:"permission"`
	// The user to grant the permission to. Changing this forces replacement.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewRegisteredModelPermission registers a new resource with the given unique name, arguments, and options.
func NewRegisteredModelPermission(ctx *pulumi.Context,
	name string, args *RegisteredModelPermissionArgs, opts ...pulumi.ResourceOption) (*RegisteredModelPermission, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Permission == nil {
		return nil, errors.New("invalid value for required argument 'Permission'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"name",
		"username",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RegisteredModelPermission
	err := ctx.RegisterResource("mlflow:auth:RegisteredModelPermission", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegisteredModelPermission gets an existing RegisteredModelPermission resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegisteredModelPermission(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegisteredModelPermissionState, opts ...pulumi.ResourceOption) (*RegisteredModelPermission, error) {
	var resource RegisteredModelPermission
	err := ctx.ReadResource("mlflow:auth:RegisteredModelPermission", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RegisteredModelPermission resources.
type registeredModelPermissionState struct {
}

type RegisteredModelPermissionState struct {
}

func (RegisteredModelPermissionState) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelPermissionState)(nil)).Elem()
}

type registeredModelPermissionArgs struct {
	// The registered model name. Changing this forces replacement.
	Name string `pulumi:"name"`
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission string `pulumi:"permission"`
	// The user to grant the permission to. Changing this forces replacement.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a RegisteredModelPermission resource.
type RegisteredModelPermissionArgs struct {
	// The registered model name. Changing this forces replacement.
	Name pulumi.StringInput
	// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
	Permission pulumi.StringInput
	// The user to grant the permission to. Changing this forces replacement.
	Username pulumi.StringInput
}

func (RegisteredModelPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredModelPermissionArgs)(nil)).Elem()
}

type RegisteredModelPermissionInput interface {
	pulumi.Input

	ToRegisteredModelPermissionOutput() RegisteredModelPermissionOutput
	ToRegisteredModelPermissionOutputWithContext(ctx context.Context) RegisteredModelPermissionOutput
}

func (*RegisteredModelPermission) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelPermission)(nil)).Elem()
}

func (i *RegisteredModelPermission) ToRegisteredModelPermissionOutput() RegisteredModelPermissionOutput {
	return i.ToRegisteredModelPermissionOutputWithContext(context.Background())
}

func (i *RegisteredModelPermission) ToRegisteredModelPermissionOutputWithContext(ctx context.Context) RegisteredModelPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelPermissionOutput)
}

// RegisteredModelPermissionArrayInput is an input type that accepts RegisteredModelPermissionArray and RegisteredModelPermissionArrayOutput values.
// You can construct a concrete instance of `RegisteredModelPermissionArrayInput` via:
//
//	RegisteredModelPermissionArray{ RegisteredModelPermissionArgs{...} }
type RegisteredModelPermissionArrayInput interface {
	pulumi.Input

	ToRegisteredModelPermissionArrayOutput() RegisteredModelPermissionArrayOutput
	ToRegisteredModelPermissionArrayOutputWithContext(context.Context) RegisteredModelPermissionArrayOutput
}

type RegisteredModelPermissionArray []RegisteredModelPermissionInput

func (RegisteredModelPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelPermission)(nil)).Elem()
}

func (i RegisteredModelPermissionArray) ToRegisteredModelPermissionArrayOutput() RegisteredModelPermissionArrayOutput {
	return i.ToRegisteredModelPermissionArrayOutputWithContext(context.Background())
}

func (i RegisteredModelPermissionArray) ToRegisteredModelPermissionArrayOutputWithContext(ctx context.Context) RegisteredModelPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelPermissionArrayOutput)
}

// RegisteredModelPermissionMapInput is an input type that accepts RegisteredModelPermissionMap and RegisteredModelPermissionMapOutput values.
// You can construct a concrete instance of `RegisteredModelPermissionMapInput` via:
//
//	RegisteredModelPermissionMap{ "key": RegisteredModelPermissionArgs{...} }
type RegisteredModelPermissionMapInput interface {
	pulumi.Input

	ToRegisteredModelPermissionMapOutput() RegisteredModelPermissionMapOutput
	ToRegisteredModelPermissionMapOutputWithContext(context.Context) RegisteredModelPermissionMapOutput
}

type RegisteredModelPermissionMap map[string]RegisteredModelPermissionInput

func (RegisteredModelPermissionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelPermission)(nil)).Elem()
}

func (i RegisteredModelPermissionMap) ToRegisteredModelPermissionMapOutput() RegisteredModelPermissionMapOutput {
	return i.ToRegisteredModelPermissionMapOutputWithContext(context.Background())
}

func (i RegisteredModelPermissionMap) ToRegisteredModelPermissionMapOutputWithContext(ctx context.Context) RegisteredModelPermissionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredModelPermissionMapOutput)
}

type RegisteredModelPermissionOutput struct{ *pulumi.OutputState }

func (RegisteredModelPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredModelPermission)(nil)).Elem()
}

func (o RegisteredModelPermissionOutput) ToRegisteredModelPermissionOutput() RegisteredModelPermissionOutput {
	return o
}

func (o RegisteredModelPermissionOutput) ToRegisteredModelPermissionOutputWithContext(ctx context.Context) RegisteredModelPermissionOutput {
	return o
}

// The registered model name. Changing this forces replacement.
func (o RegisteredModelPermissionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelPermission) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The permission level granted: `READ`, `EDIT`, `MANAGE` or `NO_PERMISSIONS`. Updatable in place.
func (o RegisteredModelPermissionOutput) Permission() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelPermission) pulumi.StringOutput { return v.Permission }).(pulumi.StringOutput)
}

// The user to grant the permission to. Changing this forces replacement.
func (o RegisteredModelPermissionOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredModelPermission) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type RegisteredModelPermissionArrayOutput struct{ *pulumi.OutputState }

func (RegisteredModelPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RegisteredModelPermission)(nil)).Elem()
}

func (o RegisteredModelPermissionArrayOutput) ToRegisteredModelPermissionArrayOutput() RegisteredModelPermissionArrayOutput {
	return o
}

func (o RegisteredModelPermissionArrayOutput) ToRegisteredModelPermissionArrayOutputWithContext(ctx context.Context) RegisteredModelPermissionArrayOutput {
	return o
}

func (o RegisteredModelPermissionArrayOutput) Index(i pulumi.IntInput) RegisteredModelPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RegisteredModelPermission {
		return vs[0].([]*RegisteredModelPermission)[vs[1].(int)]
	}).(RegisteredModelPermissionOutput)
}

type RegisteredModelPermissionMapOutput struct{ *pulumi.OutputState }

func (RegisteredModelPermissionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RegisteredModelPermission)(nil)).Elem()
}

func (o RegisteredModelPermissionMapOutput) ToRegisteredModelPermissionMapOutput() RegisteredModelPermissionMapOutput {
	return o
}

func (o RegisteredModelPermissionMapOutput) ToRegisteredModelPermissionMapOutputWithContext(ctx context.Context) RegisteredModelPermissionMapOutput {
	return o
}

func (o RegisteredModelPermissionMapOutput) MapIndex(k pulumi.StringInput) RegisteredModelPermissionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RegisteredModelPermission {
		return vs[0].(map[string]*RegisteredModelPermission)[vs[1].(string)]
	}).(RegisteredModelPermissionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelPermissionInput)(nil)).Elem(), &RegisteredModelPermission{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelPermissionArrayInput)(nil)).Elem(), RegisteredModelPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredModelPermissionMapInput)(nil)).Elem(), RegisteredModelPermissionMap{})
	pulumi.RegisterOutputType(RegisteredModelPermissionOutput{})
	pulumi.RegisterOutputType(RegisteredModelPermissionArrayOutput{})
	pulumi.RegisterOutputType(RegisteredModelPermissionMapOutput{})
}
