// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace registry {
    export interface ModelVersionResult {
        aliases: string[];
        currentStage: string;
        description: string;
        name: string;
        runId: string;
        source: string;
        status: string;
        tags: {[key: string]: string};
        version: string;
    }

    export interface RegisteredModelResult {
        creationTimestamp: number;
        description: string;
        lastUpdatedTimestamp: number;
        name: string;
        tags: {[key: string]: string};
    }

}

export namespace tracking {
    export interface ExperimentResult {
        artifactLocation: string;
        experimentId: string;
        lifecycleStage: string;
        name: string;
        tags: {[key: string]: string};
    }

}
