// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Looks up an existing MLflow experiment by its server-assigned ID. Wraps [`experiments/get`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment).
 *
 * ## Example Usage
 */
export function getExperiment(args: GetExperimentArgs, opts?: pulumi.InvokeOptions): Promise<GetExperimentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:index:getExperiment", {
        "experimentId": args.experimentId,
    }, opts);
}

export interface GetExperimentArgs {
    experimentId: string;
}

export interface GetExperimentResult {
    readonly artifactLocation: string;
    readonly experimentId: string;
    readonly lifecycleStage: string;
    readonly name: string;
    readonly tags: {[key: string]: string};
}
/**
 * Looks up an existing MLflow experiment by its server-assigned ID. Wraps [`experiments/get`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment).
 *
 * ## Example Usage
 */
export function getExperimentOutput(args: GetExperimentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetExperimentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:index:getExperiment", {
        "experimentId": args.experimentId,
    }, opts);
}

export interface GetExperimentOutputArgs {
    experimentId: pulumi.Input<string>;
}
