// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Looks up an existing MLflow experiment by its unique name. Wraps [`experiments/get-by-name`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment-by-name).
 *
 * ## Example Usage
 */
export function getExperimentByName(args: GetExperimentByNameArgs, opts?: pulumi.InvokeOptions): Promise<GetExperimentByNameResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:index:getExperimentByName", {
        "name": args.name,
    }, opts);
}

export interface GetExperimentByNameArgs {
    name: string;
}

export interface GetExperimentByNameResult {
    readonly artifactLocation: string;
    readonly experimentId: string;
    readonly lifecycleStage: string;
    readonly name: string;
    readonly tags: {[key: string]: string};
}
/**
 * Looks up an existing MLflow experiment by its unique name. Wraps [`experiments/get-by-name`](https://mlflow.org/docs/latest/api_reference/rest-api.html#get-experiment-by-name).
 *
 * ## Example Usage
 */
export function getExperimentByNameOutput(args: GetExperimentByNameOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetExperimentByNameResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:index:getExperimentByName", {
        "name": args.name,
    }, opts);
}

export interface GetExperimentByNameOutputArgs {
    name: pulumi.Input<string>;
}
