// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ExperimentArgs } from "./experiment";
export type Experiment = import("./experiment").Experiment;
export const Experiment: typeof import("./experiment").Experiment = null as any;
utilities.lazyLoad(exports, ["Experiment"], () => require("./experiment"));

export { GetExperimentArgs, GetExperimentResult, GetExperimentOutputArgs } from "./getExperiment";
export const getExperiment: typeof import("./getExperiment").getExperiment = null as any;
export const getExperimentOutput: typeof import("./getExperiment").getExperimentOutput = null as any;
utilities.lazyLoad(exports, ["getExperiment","getExperimentOutput"], () => require("./getExperiment"));

export { GetExperimentByNameArgs, GetExperimentByNameResult, GetExperimentByNameOutputArgs } from "./getExperimentByName";
export const getExperimentByName: typeof import("./getExperimentByName").getExperimentByName = null as any;
export const getExperimentByNameOutput: typeof import("./getExperimentByName").getExperimentByNameOutput = null as any;
utilities.lazyLoad(exports, ["getExperimentByName","getExperimentByNameOutput"], () => require("./getExperimentByName"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SearchExperimentsArgs, SearchExperimentsResult, SearchExperimentsOutputArgs } from "./searchExperiments";
export const searchExperiments: typeof import("./searchExperiments").searchExperiments = null as any;
export const searchExperimentsOutput: typeof import("./searchExperiments").searchExperimentsOutput = null as any;
utilities.lazyLoad(exports, ["searchExperiments","searchExperimentsOutput"], () => require("./searchExperiments"));


// Export sub-modules:
import * as auth from "./auth";
import * as config from "./config";
import * as registry from "./registry";
import * as types from "./types";

export {
    auth,
    config,
    registry,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mlflow:index:Experiment":
                return new Experiment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mlflow", "index", _module)
pulumi.runtime.registerResourcePackage("mlflow", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:mlflow") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
