// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'mlflow';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Password for HTTP Basic authentication.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
     */
    declare public readonly token: pulumi.Output<string | undefined>;
    /**
     * URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
     */
    declare public readonly trackingUri: pulumi.Output<string | undefined>;
    /**
     * Username for HTTP Basic authentication against the MLflow tracking server.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["insecureSkipVerify"] = pulumi.output(args?.insecureSkipVerify).apply(JSON.stringify);
            resourceInputs["password"] = (args?.password ? pulumi.secret(args.password) : undefined) ?? (utilities.getEnv("MLFLOW_TRACKING_PASSWORD") || "");
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? (utilities.getEnv("MLFLOW_TRACKING_TOKEN") || "");
            resourceInputs["trackingUri"] = (args?.trackingUri) ?? (utilities.getEnv("MLFLOW_TRACKING_URI") || "");
            resourceInputs["username"] = (args?.username) ?? (utilities.getEnv("MLFLOW_TRACKING_USERNAME") || "");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Skip TLS certificate verification when connecting to the tracking server. Not recommended in production.
     */
    insecureSkipVerify?: pulumi.Input<boolean | undefined>;
    /**
     * Password for HTTP Basic authentication.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * Bearer token for authenticating against the MLflow tracking server. Takes precedence over username/password.
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * URL of the MLflow tracking server, e.g. https://mlflow.example.com. May also be set via the MLFLOW_TRACKING_URI environment variable.
     */
    trackingUri?: pulumi.Input<string | undefined>;
    /**
     * Username for HTTP Basic authentication against the MLflow tracking server.
     */
    username?: pulumi.Input<string | undefined>;
}
