// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Searches MLflow experiments with an optional filter expression. Wraps [`experiments/search`](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-experiments).
 *
 * ## Example Usage
 */
export function searchExperiments(args?: SearchExperimentsArgs, opts?: pulumi.InvokeOptions): Promise<SearchExperimentsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mlflow:index:searchExperiments", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchExperimentsArgs {
    filter?: string;
    maxResults?: number;
}

export interface SearchExperimentsResult {
    readonly experiments: outputs.tracking.ExperimentResult[];
}
/**
 * Searches MLflow experiments with an optional filter expression. Wraps [`experiments/search`](https://mlflow.org/docs/latest/api_reference/rest-api.html#search-experiments).
 *
 * ## Example Usage
 */
export function searchExperimentsOutput(args?: SearchExperimentsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SearchExperimentsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mlflow:index:searchExperiments", {
        "filter": args.filter,
        "maxResults": args.maxResults,
    }, opts);
}

export interface SearchExperimentsOutputArgs {
    filter?: pulumi.Input<string | undefined>;
    maxResults?: pulumi.Input<number | undefined>;
}
